import { useEffect, useState } from 'react';
import { Button, Card, Col, Descriptions, Drawer, Form, Input, Modal, Row, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { CheckOutlined, CloseOutlined, ReloadOutlined, SafetyCertificateOutlined } from '@ant-design/icons';
import { api, idempotencyKey } from './api';
import { statusText } from './domain';
import { useIsMobile } from './responsive';
import type { User } from './App';

const safe=(v:any,fallback:any='\u6682\u65e0')=>v===undefined||v===null||v===''?fallback:v;
const docName=(v:any)=>statusText[v]||safe(v,'\u672a\u77e5\u4e1a\u52a1');
const tabs:[string,string][]=[['pendingMine','\u5f85\u6211\u5ba1\u6838'],['pendingAll','\u5168\u90e8\u5f85\u5ba1\u6838'],['approved','\u6211\u5df2\u5ba1\u6838'],['submitted','\u6211\u63d0\u4ea4\u7684'],['rejected','\u5df2\u9a73\u56de'],['all','\u5168\u90e8\u8bb0\u5f55']];
const reasons=['\u6570\u91cf\u6216\u5e93\u4f4d\u4fe1\u606f\u4e0d\u5b8c\u6574','\u5e93\u5b58\u6216\u6279\u6b21\u4fe1\u606f\u4e0d\u6b63\u786e','\u4e1a\u52a1\u5355\u636e\u586b\u5199\u6709\u8bef','\u5176\u4ed6\u539f\u56e0'];
const T={title:'\u5ba1\u6838\u4e2d\u5fc3',description:'\u5e93\u5b58\u5355\u636e\u5fc5\u987b\u7ecf\u5ba1\u6838\u901a\u8fc7\u540e\uff0c\u624d\u4f1a\u7531\u7edf\u4e00\u8fc7\u8d26\u670d\u52a1\u53d8\u66f4\u5e93\u5b58\u3002',refresh:'\u5237\u65b0',workbench:'\u5ba1\u6838\u5de5\u4f5c\u53f0',batchReject:'\u6279\u91cf\u9a73\u56de',keyword:'\u5355\u53f7 / \u7269\u6599',documentType:'\u4e1a\u52a1\u7c7b\u578b',status:'\u72b6\u6001',reset:'\u91cd\u7f6e',close:'\u5173\u95ed',reject:'\u9a73\u56de',approve:'\u5ba1\u6838\u901a\u8fc7',minute:'\u5206\u949f',overdue:'\u8d85\u65f6',details:'\u8be6\u60c5',noNumber:'\u672a\u751f\u6210\u5355\u53f7',detailTitle:'\u5ba1\u6838\u8be6\u60c5',reason:'\u9a73\u56de\u539f\u56e0',commonReason:'\u5e38\u7528\u539f\u56e0',warehouse:'\u4ed3\u5e93',submittedAt:'\u63d0\u4ea4\u65f6\u95f4',notes:'\u5907\u6ce8',item:'\u7269\u6599',location:'\u5e93\u4f4d',batch:'\u6279\u6b21',quantity:'\u6570\u91cf',confirmApprove:'\u786e\u8ba4\u5ba1\u6838\u901a\u8fc7\uff1f',approveHint:'\u901a\u8fc7\u540e\u5c06\u6309\u672c\u5355\u636e\u660e\u7ec6\u7edf\u4e00\u8fc7\u8d26\uff0c\u5e93\u5b58\u4f59\u989d\u4e0e\u4e0d\u53ef\u4fee\u6539\u6d41\u6c34\u4f1a\u540c\u6b65\u66f4\u65b0\u3002',batchRejectTitle:'\u6279\u91cf\u9a73\u56de',rejectTitle:'\u9a73\u56de\u5355\u636e',confirmReject:'\u786e\u8ba4\u9a73\u56de'};

export function ApprovalsPage({user}:{user:User}) {
  const mobile=useIsMobile(); const [tab,setTab]=useState('pendingMine'); const [stats,setStats]=useState<any>({}); const [data,setData]=useState<any>({items:[],total:0}); const [loading,setLoading]=useState(false); const [selected,setSelected]=useState<string[]>([]); const [detail,setDetail]=useState<any>(); const [drawer,setDrawer]=useState(false); const [filters,setFilters]=useState<any>({}); const [rejecting,setRejecting]=useState<'batch'|'single'|undefined>(); const [form]=Form.useForm();
  const canApprove=user.role==='ADMIN'||Boolean(user.permissions?.includes('approval.approve')); const canReject=user.role==='ADMIN'||Boolean(user.permissions?.includes('approval.reject'));
  const load=async()=>{setLoading(true);try{const query=new URLSearchParams({tab,page:'1',pageSize:'20',...Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==undefined&&v!=='')) as Record<string,string>});const [s,l]=await Promise.all([api('/approvals/statistics'),api(`/approvals?${query}`)]);setStats(s||{});setData(l||{items:[],total:0});}catch(e:any){message.error(e.message||'\u5ba1\u6838\u4e2d\u5fc3\u52a0\u8f7d\u5931\u8d25');}finally{setLoading(false);}};
  useEffect(()=>{void load();const timer=window.setInterval(load,60000);const refresh=()=>void load();window.addEventListener('inventory:refresh',refresh);return()=>{clearInterval(timer);window.removeEventListener('inventory:refresh',refresh);};},[tab,JSON.stringify(filters)]);
  const open=async(id:string)=>{try{const d=await api(`/approvals/${id}`);setDetail(d);setDrawer(true);}catch(e:any){message.error(e.message);}};
  const approve=async()=>{if(!detail)return;try{await api(`/approvals/${detail.id}/approve`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({receiptAllocations:detail.receiptAllocations||[]})});message.success('\u5ba1\u6838\u901a\u8fc7\uff0c\u5e93\u5b58\u5df2\u7edf\u4e00\u8fc7\u8d26');setDrawer(false);void load();}catch(e:any){message.error(e.message);}};
  const reject=async(values:any)=>{const ids=rejecting==='batch'?selected:detail?[detail.id]:[];if(!ids.length)return;try{const path=rejecting==='batch'?'/approvals/batch-reject':`/approvals/${ids[0]}/reject`;const body=rejecting==='batch'?{documentIds:ids,reason:values.reason,reasonCode:values.reasonCode}:{reason:values.reason,reasonCode:values.reasonCode};await api(path,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify(body)});message.success('\u5df2\u9a73\u56de');setRejecting(undefined);setDrawer(false);setSelected([]);form.resetFields();void load();}catch(e:any){message.error(e.message);}};
  const statistics:[string,string,string][]=[['\u5f85\u6211\u5ba1\u6838','pendingMine',''],['\u8303\u56f4\u5185\u5f85\u5ba1','pendingAll',''],['\u4eca\u65e5\u5df2\u5ba1\u6838','approvedToday','green'],['\u4eca\u65e5\u5df2\u9a73\u56de','rejectedToday','red'],['\u8d85\u65f6\u5f85\u5ba1','overdue','orange'],['\u672c\u6708\u5df2\u5ba1\u6838','approvedMonth','green']];
  const columns:any[]=[{title:'\u5355\u636e\u7f16\u53f7',dataIndex:'documentNo',render:(v:any,r:any)=><Button type="link" onClick={()=>open(r.id)}>{safe(v,T.noNumber)}</Button>},{title:'\u4e1a\u52a1\u7c7b\u578b',dataIndex:'documentType',render:docName},{title:'\u4ed3\u5e93',render:(_:any,r:any)=>`${safe(r.warehouseCode,'\u672a\u547d\u540d\u4ed3\u5e93')} ${safe(r.warehouseName,'')}`},{title:'\u4e1a\u52a1\u6458\u8981',render:(_:any,r:any)=>safe(r.notes,`${safe(r.lineCount,0)} \u6761\u7269\u6599\u660e\u7ec6`)},{title:'\u63d0\u4ea4\u4eba',dataIndex:'submitterName',render:(v:any)=>safe(v,'\u672a\u77e5')},{title:'\u63d0\u4ea4\u65f6\u95f4',dataIndex:'submittedAt',render:(v:any)=>safe(v,'\u672a\u63d0\u4ea4')},{title:'\u7b49\u5f85\u65f6\u957f',render:(_:any,r:any)=>r.status==='SUBMITTED'?<>{safe(r.waitingMinutes,0)} {T.minute} {Number(r.waitingMinutes||0)>=1440&&<Tag color="orange">{T.overdue}</Tag>}</>:'-'},{title:'\u72b6\u6001',dataIndex:'status',render:(v:any)=><Tag color={v==='SUBMITTED'?'blue':v==='REJECTED'?'red':v==='POSTED'?'green':'default'}>{statusText[v]||safe(v)}</Tag>},{title:'\u64cd\u4f5c',render:(_:any,r:any)=><Button size="small" onClick={()=>open(r.id)}>{T.details}</Button>}];
  return <div className="approvals-page"><div className="page-heading"><div><Typography.Title level={2}>{T.title}</Typography.Title><Typography.Text type="secondary">{T.description}</Typography.Text></div><Button icon={<ReloadOutlined/>} onClick={load}>{T.refresh}</Button></div>
    <Row gutter={[12,12]} className="approval-stats">{statistics.map(([title,key,color])=><Col xs={12} sm={8} lg={4} key={key}><Card hoverable onClick={()=>setTab(key==='pendingMine'?'pendingMine':key==='pendingAll'||key==='overdue'?'pendingAll':key==='approvedToday'||key==='approvedMonth'?'approved':'rejected')}><Statistic title={title} value={Number(stats[key]||0)} valueStyle={{color:color||undefined}}/></Card></Col>)}</Row>
    <Card className="approval-workbench" title={<Space><SafetyCertificateOutlined/>{T.workbench}</Space>} extra={canReject&&selected.length?<Button danger icon={<CloseOutlined/>} onClick={()=>setRejecting('batch')}>{T.batchReject} ({selected.length})</Button>:null}>
      <div className="approval-tabs">{tabs.map(([key,label])=><Button key={key} type={tab===key?'primary':'text'} onClick={()=>setTab(key)}>{label}</Button>)}</div>
      <Space wrap className="approval-filters"><Input placeholder={T.keyword} allowClear onChange={e=>setFilters((f:any)=>({...f,keyword:e.target.value}))}/><Select allowClear placeholder={T.documentType} style={{minWidth:160}} options={Object.entries(statusText).filter(([k])=>k.includes('_')).map(([value,label])=>({value,label}))} onChange={v=>setFilters((f:any)=>({...f,documentType:v}))}/><Select allowClear placeholder={T.status} style={{minWidth:110}} options={['SUBMITTED','POSTED','REJECTED','VOIDED'].map(value=>({value,label:statusText[value]}))} onChange={v=>setFilters((f:any)=>({...f,status:v}))}/><Button onClick={()=>setFilters({})}>{T.reset}</Button></Space>
      <Table rowKey="id" loading={loading} columns={columns} dataSource={data.items||[]} scroll={{x:1050}} pagination={{total:data.total||0,pageSize:20}} rowSelection={canReject?{selectedRowKeys:selected,onChange:v=>setSelected(v as string[]),getCheckboxProps:(r:any)=>({disabled:r.status!=='SUBMITTED'})}:undefined}/>
    </Card>
    <Drawer title={`${T.detailTitle} - ${safe(detail?.documentNo,T.noNumber)}`} width={mobile?'100%':800} open={drawer} onClose={()=>setDrawer(false)} footer={<Space style={{display:'flex',justifyContent:'flex-end'}}><Button onClick={()=>setDrawer(false)}>{T.close}</Button>{detail?.status==='SUBMITTED'&&canReject&&<Button danger onClick={()=>setRejecting('single')}>{T.reject}</Button>}{detail?.status==='SUBMITTED'&&canApprove&&<Button type="primary" icon={<CheckOutlined/>} onClick={()=>Modal.confirm({title:'确认审核通过？',content:'通过后将按本单据明细统一过账，库存余额与不可修改流水会同步更新。',onOk:approve})}>{T.approve}</Button>}</Space>}>
      {detail&&<><Descriptions column={mobile?1:2} bordered size="small"><Descriptions.Item label={T.documentType}>{docName(detail.documentType)}</Descriptions.Item><Descriptions.Item label={T.status}>{statusText[detail.status]||detail.status}</Descriptions.Item><Descriptions.Item label={T.warehouse}>{safe(detail.warehouseCode,'\u672a\u547d\u540d\u4ed3\u5e93')} {safe(detail.warehouseName,'')}</Descriptions.Item><Descriptions.Item label={T.submittedAt}>{safe(detail.submittedAt,'\u672a\u63d0\u4ea4')}</Descriptions.Item><Descriptions.Item label={T.notes} span={2}>{safe(detail.notes,'\u65e0')}</Descriptions.Item></Descriptions><Table className="approval-line-table" size="small" rowKey="id" pagination={false} dataSource={detail.lines||[]} columns={[{title:T.item,render:(_:any,r:any)=>`${safe(r.itemCode,'\u672a\u7f16\u7801')} ${safe(r.itemName,'\u672a\u547d\u540d\u7269\u6599')}`},{title:T.location,render:(_:any,r:any)=>safe(r.locationCode,'\u672a\u547d\u540d\u5e93\u4f4d')},{title:T.batch,dataIndex:'batchNo',render:(v:any)=>safe(v,'-')},{title:T.quantity,dataIndex:'quantity',render:(v:any,r:any)=>`${safe(v,0)} ${safe(r.unit,'')}`}]}/>{detail.rejectionReason&&<Card size="small" className="reject-reason">{T.reason}：{detail.rejectionReason}</Card>}</>}
    </Drawer>
    <Modal title={rejecting==='batch'?T.batchRejectTitle:T.rejectTitle} open={Boolean(rejecting)} onCancel={()=>setRejecting(undefined)} onOk={()=>form.submit()} okText={T.confirmReject} okButtonProps={{danger:true}}><Form form={form} layout="vertical" onFinish={reject}><Form.Item name="reasonCode" label={T.commonReason}><Select allowClear options={reasons.map(value=>({value,label:value}))}/></Form.Item><Form.Item name="reason" label={T.reason} rules={[{required:true,message:'\u8bf7\u586b\u5199\u9a73\u56de\u539f\u56e0'},{max:500,message:'\u6700\u591a 500 \u5b57'}]}><Input.TextArea rows={4} maxLength={500}/></Form.Item></Form></Modal>
  </div>;
}
