import { useEffect, useMemo, useState } from 'react';
import dayjs from 'dayjs';
import { useParams } from 'react-router-dom';
import { Alert, Badge, Button, Card, Descriptions, Drawer, Form, Input, InputNumber, Modal, Select, Space, Tag, Typography, message } from 'antd';
import { DownloadOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { API_BASE, api, idempotencyKey, token } from './api';
import { PageScaffold, StatusTag } from './components';
import { formatBeijingTime, formatQuantity, statusText } from './domain';
import { ResponsiveTable as Table, useIsMobile } from './responsive';
import type { User } from './App';

const fail=(error:any)=>message.error(error?.message||'操作失败');
const quantity=(value:any)=>String(value??'0');

export function ProductionPickingPage({user}:{user:User}) {
  const {id}=useParams(); const mobile=useIsMobile();
  const [data,setData]=useState<any>(); const [shortage,setShortage]=useState<any>({items:[],shortageCount:0});
  const [warehouses,setWarehouses]=useState<any[]>([]); const [locations,setLocations]=useState<any[]>([]); const [balances,setBalances]=useState<any[]>([]);
  const [mode,setMode]=useState<'manual'|'auto'>(); const [picking,setPicking]=useState<any>(); const [drawer,setDrawer]=useState(false);
  const [operation,setOperation]=useState<'return'|'complete'>(); const [form]=Form.useForm(); const [autoForm]=Form.useForm(); const [operationForm]=Form.useForm();
  const canIssue=user.role==='ADMIN'||Boolean(user.permissions?.includes('production.issue'));
  const canComplete=user.role==='ADMIN'||Boolean(user.permissions?.includes('production.complete'));
  const canManage=user.role==='ADMIN'||Boolean(user.permissions?.includes('production.manage'));
  const load=async()=>{try{const [order,w,l,b]=await Promise.all([api(`/production-orders/${id}`),api('/warehouses'),api('/warehouse-locations?pageSize=100'),api('/inventory/balances?page=1&pageSize=100')]);setData(order);setWarehouses((w||[]).filter((x:any)=>x.status==='ACTIVE'));setLocations((l.items||[]).map((row:any)=>({...row,warehouseId:row.warehouseId||row.warehouse_id,zoneId:row.zoneId||row.zone_id,zoneCode:row.zoneCode||row.zone_code,archived:row.archived??row.is_archived})).filter((row:any)=>row.status==='ACTIVE'&&!row.archived));setBalances(b.items||[]);const result=await api(`/production-orders/${id}/material-shortage`);setShortage({items:result,shortageCount:result.filter((x:any)=>Number(x.shortageQty)>0).length});}catch(error){fail(error);}};
  useEffect(()=>{void load();},[id]);
  const actionable=['RELEASED','IN_PROGRESS'].includes(data?.status);
  const rawWarehouses=warehouses.filter(row=>row.warehouseType==='RAW').map(row=>({value:row.id,label:`${row.warehouseCode} ${row.name}`}));
  const materialOptions=(shortage.items||[]).filter((row:any)=>Number(row.pendingQty)>0).map((row:any)=>({value:row.materialId,label:`${row.itemCode} ${row.itemName}（待领 ${formatQuantity(row.pendingQty)}）`}));

  const check=async()=>{try{const result=await api(`/production-orders/${id}/material-shortage/check`,{method:'POST'});setShortage(result);message.success(result.hasShortage?`检查完成：${result.shortageCount} 种物料缺料`:'检查完成：当前物料库存充足');}catch(error){fail(error);}};
  const exportShortage=async()=>{try{const response=await fetch(`${API_BASE}/production-orders/${id}/material-shortage/export`,{headers:{Authorization:`Bearer ${token()}`}});if(!response.ok)throw new Error('缺料清单导出失败');const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${data.orderNo}-缺料清单.csv`;link.click();URL.revokeObjectURL(url);}catch(error){fail(error);}};
  const startManual=()=>{void check();setPicking(undefined);form.resetFields();form.setFieldsValue({defaultWarehouseId:data.defaultIssueWarehouseId||warehouses[0]?.id,allocations:[{}]});setMode('manual');};
  const startAuto=()=>{void check();setPicking(undefined);autoForm.resetFields();autoForm.setFieldsValue({defaultWarehouseId:data.defaultIssueWarehouseId||warehouses[0]?.id,spares:(shortage.items||[]).map((row:any)=>({materialId:row.materialId,quantity:0}))});setMode('auto');};
  const groupAllocations=(values:any)=>{const grouped=new Map<string,any>();for(const row of values.allocations||[]){if(!row.materialId)continue;const material=grouped.get(row.materialId)||{materialId:row.materialId,normalQty:'0',spareQty:'0',allocations:[]};material.normalQty=String(Number(material.normalQty)+Number(row.normalQty||0));material.spareQty=String(Number(material.spareQty)+Number(row.spareQty||0));material.allocations.push({warehouseId:row.warehouseId,locationId:row.locationId,batchId:row.batchId,normalQty:String(row.normalQty||0),spareQty:String(row.spareQty||0)});grouped.set(row.materialId,material);}return[...grouped.values()];};
  const createManual=async(values:any)=>{try{const doc=await api(`/production-orders/${id}/picking-orders/manual`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({defaultWarehouseId:values.defaultWarehouseId,notes:values.notes,materials:groupAllocations(values)})});message.success('手动领料草稿已创建');setMode(undefined);await showPicking(doc.id);await load();}catch(error){fail(error);}};
  const createAuto=async(values:any)=>{try{const doc=await api(`/production-orders/${id}/picking-orders/auto-generate`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({defaultWarehouseId:values.defaultWarehouseId,notes:values.notes,spares:(values.spares||[]).map((row:any)=>({materialId:row.materialId,quantity:String(row.quantity||0)}))})});message.success('一键领料草稿已生成，请核对分配结果');setMode(undefined);await showPicking(doc.id);await load();}catch(error){fail(error);}};
  const showPicking=async(documentId:string)=>{try{const doc=await api(`/picking-orders/${documentId}`);setPicking(doc);setDrawer(true);}catch(error){fail(error);}};
  const changePicking=async(action:'submit'|'withdraw'|'cancel'|'resubmit')=>{try{const doc=await api(`/picking-orders/${picking.id}/${action}`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()}});setPicking(doc);message.success(action==='submit'||action==='resubmit'?'领料单已提交审核':action==='withdraw'?'领料单已撤回':'领料单已撤销');await load();}catch(error){fail(error);}};
  const reallocate=async()=>{try{const doc=await api(`/picking-orders/${picking.id}/auto-allocate`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({spares:picking.materials.map((row:any)=>({materialId:row.materialId,quantity:row.spareQty}))})});setPicking(doc);message.success('已按实时库存重新分配');await load();}catch(error){fail(error);}};
  const editPicking=()=>{const allocations=(picking.allocations||[]).map((row:any)=>({materialId:row.materialId,warehouseId:row.warehouseId,locationId:row.locationId,batchId:row.batchId,normalQty:Number(row.normalQty),spareQty:Number(row.spareQty)}));form.setFieldsValue({defaultWarehouseId:picking.defaultWarehouseId,notes:picking.notes,allocations});setDrawer(false);setMode('manual');};
  const savePicking=async(values:any)=>{try{const doc=await api(`/picking-orders/${picking.id}`,{method:'PUT',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify({notes:values.notes,materials:groupAllocations(values)})});message.success('领料草稿已保存');setMode(undefined);await showPicking(doc.id);await load();}catch(error){fail(error);}};
  const locationOptions=(warehouseId:string,itemId:string)=>balances.filter((row:any)=>row.warehouseId===warehouseId&&row.itemId===itemId&&Number(row.availableQty)>0).map((row:any)=>({value:row.locationId,label:`${row.zoneCode} / ${row.locationCode}｜可用 ${formatQuantity(row.availableQty)} ${row.unit}`,batchId:row.batchId,batchNo:row.batchNo}));
  const submitOperation=async(values:any)=>{try{const payload=operation==='complete'?{warehouseId:values.warehouseId,locationId:values.locationId,batchId:values.batchId,quantity:String(values.quantity),notes:values.notes}:{warehouseId:values.warehouseId,lines:(values.lines||[]).map((row:any)=>({materialId:row.materialId,locationId:row.locationId,batchId:row.batchId,quantity:String(row.quantity)})),notes:values.notes};await api(`/production-orders/${id}/${operation}`,{method:'POST',headers:{'Idempotency-Key':idempotencyKey()},body:JSON.stringify(payload)});message.success(operation==='complete'?'完工报产单已提交审核':'生产退料单已提交审核');setOperation(undefined);await load();}catch(error){fail(error);}};
  const cancelOrder=()=>Modal.confirm({title:'确认取消生产任务？',content:'存在未退净领料或待审核单据时系统会拒绝取消。',onOk:async()=>{try{await api(`/production-orders/${id}/cancel`,{method:'POST',body:JSON.stringify({reason:'页面取消生产任务'})});message.success('生产任务已取消');await load();}catch(error){fail(error);}}});

  if(!data)return <PageScaffold title="生产任务详情"><span>加载中...</span></PageScaffold>;
  const missing=(shortage.items||[]).filter((row:any)=>Number(row.shortageQty)>0);
  return <PageScaffold title="生产任务详情" subtitle="领料草稿提交后预占库存，审核通过后才会实际扣减并更新任务累计。" bare>
    {missing.length>0&&<Alert type="warning" showIcon message={`当前存在 ${missing.length} 种缺料物料`} description={<Space wrap>{missing.map((row:any)=><Tag color="red" key={row.materialId}>{row.itemCode} 至少补充 {formatQuantity(row.shortageQty)} {row.unit}</Tag>)}<Button size="small" onClick={exportShortage} icon={<DownloadOutlined/>}>导出缺料清单</Button></Space>} style={{marginBottom:12}}/>}
    <Card><div className="toolbar"><Space wrap><Badge count={shortage.shortageCount||0}><Button icon={<ReloadOutlined/>} onClick={check}>缺料检查</Button></Badge>{actionable&&canIssue&&<><Button type="primary" onClick={startManual}>手动领料</Button><Button type="primary" ghost onClick={startAuto}>一键领料</Button><Button onClick={()=>{operationForm.resetFields();operationForm.setFieldsValue({warehouseId:warehouses.find((row:any)=>row.warehouseType==='RAW')?.id,lines:[{}]});setOperation('return');}}>生产退料</Button></>}{actionable&&canComplete&&<Button onClick={()=>{operationForm.resetFields();operationForm.setFieldsValue({warehouseId:warehouses.find((row:any)=>row.warehouseType==='FG')?.id});setOperation('complete');}}>完工报产</Button>}{['DRAFT','RELEASED','IN_PROGRESS'].includes(data.status)&&canManage&&<Button danger onClick={cancelOrder}>取消任务</Button>}</Space></div>
      <Descriptions column={{xs:1,md:3}} items={[{label:'任务单号',children:data.orderNo},{label:'成品',children:`${data.finishedGoodCode} ${data.finishedGoodName}`},{label:'计划数量',children:formatQuantity(data.plannedQty)},{label:'累计完工',children:formatQuantity(data.completedQty)},{label:'状态',children:<StatusTag value={data.status}/>},{label:'计划日期',children:data.plannedDate||'-'}]}/></Card>
    <Card title="BOM 快照、实际累计与缺料" style={{marginTop:12}}><Table rowKey="materialId" pagination={false} dataSource={shortage.items||[]} columns={[
      {title:'物料',render:(_:any,row:any)=><span><strong>{row.itemCode}</strong><small className="table-subtext">{row.itemName}<br/>{row.model||row.spec||'无型号规格'}</small></span>},
      {title:'BOM需求',dataIndex:'requiredQty',align:'right',render:formatQuantity},{title:'已领',dataIndex:'issuedQty',align:'right',render:formatQuantity},{title:'已退',dataIndex:'returnedQty',align:'right',render:formatQuantity},
      {title:'净领料',dataIndex:'netIssuedQty',align:'right',render:formatQuantity},{title:'本次待领',dataIndex:'pendingQty',align:'right',render:formatQuantity},{title:'可用库存',dataIndex:'availableQty',align:'right',render:formatQuantity},
      {title:'缺料',dataIndex:'shortageQty',align:'right',render:(value:any)=><Typography.Text type={Number(value)>0?'danger':undefined}>{formatQuantity(value)}</Typography.Text>},
      {title:'备用件累计',dataIndex:'spareIssuedQty',align:'right',render:formatQuantity},{title:'状态',dataIndex:'status',render:(value:string)=><Tag color={value==='SATISFIED'?'green':value==='PARTIAL'?'orange':'red'}>{value==='SATISFIED'?'充足':value==='PARTIAL'?'部分缺料':'完全缺料'}</Tag>},
    ]}/></Card>
    <Card title="关联库存单据" style={{marginTop:12}}><Table rowKey="id" pagination={false} dataSource={data.documents||[]} columns={[
      {title:'单号',dataIndex:'documentNo'},{title:'类型',dataIndex:'documentType',render:(value:string)=>statusText[value]||value},{title:'方式',dataIndex:'issueMode',render:(value:string)=>value==='AUTO'?'一键领料':value==='MANUAL'?'手动领料':'-'},{title:'状态',dataIndex:'status',render:(value:string)=><StatusTag value={value}/>},
      {title:'提交时间',dataIndex:'submittedAt',render:formatBeijingTime},{title:'驳回原因',dataIndex:'rejectionReason',render:(value:any)=>value||'-'},
      {title:'操作',render:(_:any,row:any)=>row.documentType==='PRODUCTION_ISSUE'?<Button type="link" onClick={()=>showPicking(row.id)}>查看与处理</Button>:'-'},
    ]}/></Card>
    <Modal width={mobile?'calc(100vw - 16px)':920} title={picking?'编辑生产领料草稿':'手动领料'} open={mode==='manual'} onCancel={()=>setMode(undefined)} onOk={()=>form.submit()} destroyOnHidden>
      <Form form={form} layout="vertical" onFinish={picking?savePicking:createManual}>
        <Form.Item label="默认领料仓库" name="defaultWarehouseId" rules={[{required:true}]}><Select options={rawWarehouses}/></Form.Item>
        <Form.List name="allocations">{(fields,{add,remove})=><>{fields.map(field=><Card size="small" key={field.key} style={{marginBottom:10}}><Form.Item noStyle shouldUpdate>{({getFieldValue})=>{const row=getFieldValue(['allocations',field.name])||{};const requested=Number(row.normalQty||0)+Number(row.spareQty||0);const locations=locationOptions(row.warehouseId,row.materialId).filter((location:any)=>Number(location.availableQty||0)>=requested);return <>
          <Space wrap align="start"><Form.Item {...field} label="仓库" name={[field.name,'warehouseId']} rules={[{required:true}]}><Select style={{width:190}} options={rawWarehouses}/></Form.Item><Form.Item {...field} label="物料" name={[field.name,'materialId']} rules={[{required:true}]}><Select showSearch optionFilterProp="label" style={{width:240}} options={materialOptions}/></Form.Item><Form.Item {...field} label="正常领取" name={[field.name,'normalQty']} rules={[{required:true}]}><InputNumber min={0} precision={0}/></Form.Item><Form.Item {...field} label="备用件" name={[field.name,'spareQty']}><InputNumber min={0} precision={0}/></Form.Item></Space>
          <Space wrap align="start"><Form.Item {...field} label="库区 / 库位" name={[field.name,'locationId']} rules={[{required:true}]}><Select style={{width:330}} options={locations}/></Form.Item><Form.Item {...field} label="批次（可选）" name={[field.name,'batchId']}><Select allowClear style={{width:200}} options={locations.filter((x:any)=>x.batchId).map((x:any)=>({value:x.batchId,label:x.batchNo}))}/></Form.Item>{fields.length>1&&<Button danger onClick={()=>remove(field.name)}>删除明细</Button>}</Space>
        </>;}}</Form.Item></Card>)}<Button block type="dashed" icon={<PlusOutlined/>} onClick={()=>add()}>增加拆分明细</Button></>}</Form.List>
        <Form.Item label="备注" name="notes"><Input.TextArea maxLength={500}/></Form.Item>
      </Form>
    </Modal>
    <Modal width={mobile?'calc(100vw - 16px)':760} title="一键领料" open={mode==='auto'} onCancel={()=>setMode(undefined)} onOk={()=>autoForm.submit()} destroyOnHidden>
      <Form form={autoForm} layout="vertical" onFinish={createAuto}><Form.Item label="优先领料仓库" name="defaultWarehouseId" rules={[{required:true}]}><Select options={rawWarehouses}/></Form.Item><Form.List name="spares">{fields=><>{fields.map((field,index)=>{const row=shortage.items[index];return <Card size="small" key={field.key} style={{marginBottom:8}}><Form.Item {...field} name={[field.name,'materialId']} hidden><Input/></Form.Item><Space wrap><strong>{row?.itemCode} {row?.itemName}</strong><span>待领 {formatQuantity(row?.pendingQty)}</span><Form.Item {...field} label="备用件数量" name={[field.name,'quantity']}><InputNumber min={0} max={Math.floor(Number(row?.requiredQty||0)*0.1)} precision={0}/></Form.Item></Space></Card>;})}</>}</Form.List><Form.Item label="备注" name="notes"><Input.TextArea maxLength={500}/></Form.Item></Form>
    </Modal>
    <Modal width={mobile?'calc(100vw - 16px)':760} title={operation==='return'?'生产退料':'完工报产'} open={Boolean(operation)} onCancel={()=>setOperation(undefined)} onOk={()=>operationForm.submit()} destroyOnHidden>
      <Form form={operationForm} layout="vertical" onFinish={submitOperation}>
        {operation==='complete'?<><Form.Item label="本次完工数量" name="quantity" rules={[{required:true}]}><InputNumber min={1} max={Number(data.plannedQty)-Number(data.completedQty)} precision={0} style={{width:'100%'}}/></Form.Item><Typography.Text type="secondary">提交后由审核中心确定正常品、不良品以及最终仓库和库位。</Typography.Text></>:<><Form.Item label="原材料仓库" name="warehouseId" rules={[{required:true}]}><Select options={rawWarehouses}/></Form.Item><Form.List name="lines">{(fields,{add,remove})=><>{fields.map(field=><Card size="small" key={field.key} style={{marginBottom:8}}><Space wrap><Form.Item {...field} label="物料" name={[field.name,'materialId']} rules={[{required:true}]}><Select style={{width:230}} options={(shortage.items||[]).filter((row:any)=>Number(row.netIssuedQty)>0).map((row:any)=>({value:row.materialId,label:`${row.itemCode} ${row.itemName}（净领 ${formatQuantity(row.netIssuedQty)}）`}))}/></Form.Item><Form.Item {...field} label="退料数量" name={[field.name,'quantity']} rules={[{required:true}]}><InputNumber min={1} precision={0}/></Form.Item><Form.Item {...field} label="退回库位" name={[field.name,'locationId']} rules={[{required:true}]}><Select style={{width:220}} options={locations.filter((row:any)=>row.warehouseId===operationForm.getFieldValue('warehouseId')).map((row:any)=>({value:row.id,label:`${row.zoneCode||''} / ${row.code}`}))}/></Form.Item>{fields.length>1&&<Button danger onClick={()=>remove(field.name)}>删除</Button>}</Space></Card>)}<Button block type="dashed" onClick={()=>add()}>增加退料明细</Button></>}</Form.List></>}<Form.Item label="备注" name="notes"><Input.TextArea maxLength={500}/></Form.Item>
      </Form>
    </Modal>
    <Drawer width={mobile?'100%':860} title={`生产领料单 ${picking?.documentNo||''}`} open={drawer} onClose={()=>setDrawer(false)} extra={picking&&<StatusTag value={picking.status}/>}>
      {picking&&<><Descriptions column={mobile?1:3} items={[{label:'领料方式',children:picking.issueMode==='AUTO'?'一键领料':'手动领料'},{label:'状态',children:<StatusTag value={picking.status}/>},{label:'驳回原因',children:picking.rejectionReason||'-'}]}/>
        <Table rowKey="materialId" pagination={false} dataSource={picking.materials||[]} columns={[{title:'物料',render:(_:any,row:any)=>`${row.itemCode} ${row.itemName}`},{title:'本次应领',dataIndex:'pendingQty',render:formatQuantity},{title:'正常分配',dataIndex:'normalAllocatedQty',render:formatQuantity},{title:'备用件',dataIndex:'spareAllocatedQty',render:formatQuantity},{title:'缺料',dataIndex:'shortageQty',render:formatQuantity}]}/>
        <Typography.Title level={5}>仓库与库位分配</Typography.Title><Table rowKey="id" pagination={false} dataSource={picking.allocations||[]} columns={[{title:'物料',dataIndex:'materialId',render:(value:any)=>picking.materials.find((x:any)=>x.materialId===value)?.itemCode||'未命名物料'},{title:'仓库',dataIndex:'warehouseCode'},{title:'库区 / 库位',render:(_:any,row:any)=>`${row.zoneCode} / ${row.locationCode}`},{title:'批次',dataIndex:'batchNo',render:(value:any)=>value||'-'},{title:'正常',dataIndex:'normalQty',render:formatQuantity},{title:'备用件',dataIndex:'spareQty',render:formatQuantity}]}/>
        <Space wrap style={{marginTop:16}}>{['DRAFT','REJECTED'].includes(picking.status)&&<><Button onClick={editPicking}>编辑</Button><Button onClick={reallocate}>重新自动分配</Button><Button type="primary" onClick={()=>changePicking(picking.status==='REJECTED'?'resubmit':'submit')}>{picking.status==='REJECTED'?'重新提交审核':'提交审核'}</Button></>}{picking.status==='SUBMITTED'&&<Button onClick={()=>changePicking('withdraw')}>撤回修改</Button>}{['DRAFT','SUBMITTED','REJECTED'].includes(picking.status)&&<Button danger onClick={()=>changePicking('cancel')}>撤销单据</Button>}</Space></>}
    </Drawer>
  </PageScaffold>;
}
