import { useEffect, useMemo, useRef, useState } from 'react';
import * as echarts from 'echarts';
import { DndContext } from '@dnd-kit/core';
import { Layer, Rect, Stage, Text } from 'react-konva';
import { motion } from 'motion/react';
import { Alert, Button, Card, Descriptions, Drawer, Empty, Modal, Segmented, Space, Table, Tabs, Tag, message } from 'antd';
import { ApartmentOutlined, ArrowsAltOutlined, CompressOutlined, DatabaseOutlined, EditOutlined, InboxOutlined, MinusOutlined, PlusOutlined, ReloadOutlined, SaveOutlined, SwapOutlined } from '@ant-design/icons';
import { useLocation, useNavigate } from 'react-router-dom';
import { api } from './api';
import { PageScaffold } from './components';
import { formatBeijingTime, formatQuantity } from './domain';
import { LocationName, locationActualPosition, locationDisplayName } from './location-name';
import { limitRecentRecords, mapCanvasHeight, topMaterialsByUnit } from './virtual-warehouse-model';

type User = { role?: string; permissions?: string[] };
type Mode = 'ZONE' | 'LOCATION';
type View = { x: number; y: number; scale: number };
type Operation = 'inbound' | 'outbound' | 'move' | 'count';

const label: Record<string, string> = { DISABLED: '已停用', FULL: '满库', LOCKED: '库存锁定', WARNING: '容量预警', LOW: '低库存', NORMAL: '正常', EMPTY: '空库位', MATERIAL_INBOUND: '原材料入库', FINISHED_INBOUND: '成品入库', FINISHED_OUTBOUND: '成品出库', STOCK_MOVE: '移库', STOCK_CHECK: '盘点', DRAFT: '草稿', SUBMITTED: '待审批', POSTED: '已过账', REJECTED: '已驳回' };
const color: Record<string, string> = { DISABLED: '#aeb7c4', FULL: '#ff4d4f', LOCKED: '#9254de', WARNING: '#fa8c16', LOW: '#f0b429', NORMAL: '#52c41a', EMPTY: '#69b1ff' };
const n = (value: any) => Number(value || 0);
const show = (value: any, fallback = '—') => String(value || '').trim() || fallback;
const can = (user: User | undefined, permission: string) => user?.role === 'ADMIN' || Boolean(user?.permissions?.includes(permission));

const grid = (rows: any[]) => {
  const columns = Math.max(1, Math.ceil(Math.sqrt(Math.max(1, rows.length))));
  return rows.map((row, index) => ({ ...row, x: row.x ?? 32 + (index % columns) * 168, y: row.y ?? 24 + Math.floor(index / columns) * 102, width: row.width ?? 146, height: row.height ?? 76 }));
};

function HorizontalChart({ rows, onPick }: { rows: any[]; onPick: (row: any) => void }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!ref.current || !rows.length) return;
    const chart = echarts.init(ref.current);
    chart.setOption({ animationDuration: 180, grid: { top: 12, right: 38, bottom: 10, left: 128 }, tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } }, xAxis: { type: 'value', minInterval: 1, splitLine: { lineStyle: { color: '#edf1f7' } } }, yAxis: { type: 'category', inverse: true, data: rows.map(row => row.materialCode), axisTick: { show: false }, axisLine: { show: false }, axisLabel: { color: '#52637a' } }, series: [{ type: 'bar', data: rows.map(row => n(row.quantity)), barMaxWidth: 16, label: { show: true, position: 'right', color: '#52637a', formatter: ({ value }: any) => formatQuantity(value) }, itemStyle: { color: '#1677ff', borderRadius: [0, 5, 5, 0] } }] });
    chart.on('click', (event: any) => rows[event.dataIndex] && onPick(rows[event.dataIndex]));
    const watcher = new ResizeObserver(() => chart.resize()); watcher.observe(ref.current);
    return () => { watcher.disconnect(); chart.dispose(); };
  }, [rows, onPick]);
  return rows.length ? <div className="virtual-unit-chart virtual-unit-chart-horizontal" style={{ height: Math.max(166, rows.length * 29 + 28) }} ref={ref} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前库区暂无库存物料" />;
}

function Canvas({ rows, selected, mode, editing, pick, move, view, setView, onHover, fullscreen = false }: any) {
  const host = useRef<HTMLDivElement>(null);
  const [width, setWidth] = useState(700);
  const nodes = grid(rows);
  const height = mapCanvasHeight(nodes, fullscreen);
  useEffect(() => { const update = () => setWidth(host.current?.clientWidth || 700); update(); const watcher = new ResizeObserver(update); if (host.current) watcher.observe(host.current); return () => watcher.disconnect(); }, []);
  const zoom = (factor: number) => setView((old: View) => ({ ...old, scale: Math.max(.55, Math.min(1.8, old.scale * factor)) }));
  return <div className={`virtual-konva-wrap${fullscreen ? ' is-expanded' : ''}`} style={{ height }} ref={host}>
    <div className="virtual-canvas-tools"><Button size="small" icon={<CompressOutlined />} aria-label="适配地图" onClick={() => setView({ x: 0, y: 0, scale: 1 })}>适配</Button><Button size="small" icon={<PlusOutlined />} aria-label="放大地图" onClick={() => zoom(1.15)} /><Button size="small" icon={<MinusOutlined />} aria-label="缩小地图" onClick={() => zoom(.87)} />{!fullscreen && <Button size="small" icon={<ArrowsAltOutlined />} aria-label="展开地图" onClick={() => pick('__expand__')} />}</div>
    <DndContext><Stage width={width} height={height} draggable={!editing} x={view.x} y={view.y} scaleX={view.scale} scaleY={view.scale} onDragEnd={(event: any) => { if (event.target === event.currentTarget) setView((old: View) => ({ ...old, x: event.target.x(), y: event.target.y() })); }} onWheel={(event: any) => { event.evt.preventDefault(); zoom(event.evt.deltaY > 0 ? .92 : 1.08); }}><Layer>{nodes.map((row: any) => { const id = row.id || row.locationId, state = row.state || row.status || 'EMPTY', active = id === selected; return <Rect key={id} x={row.x} y={row.y} width={row.width} height={row.height} cornerRadius={8} fill={active ? '#e6f4ff' : '#fff'} stroke={active ? '#1677ff' : color[state] || color.EMPTY} strokeWidth={active ? 3 : 1.5} shadowBlur={active ? 7 : 1} shadowOpacity={.13} draggable={editing} onClick={() => pick(id)} onTap={() => pick(id)} onDblClick={() => pick(id)} onMouseEnter={() => onHover?.(mode === 'LOCATION' ? row : undefined)} onMouseLeave={() => onHover?.(undefined)} onDragEnd={(event: any) => move(id, { x: event.target.x(), y: event.target.y() })} />; })}{nodes.map((row: any) => { const state = row.state || row.status || 'EMPTY'; return <Text key={`text-${row.id || row.locationId}`} x={row.x + 10} y={row.y + 9} width={row.width - 20} fontSize={12} fontFamily="Microsoft YaHei" lineHeight={1.5} fill="#23324a" listening={false} text={`${mode === 'ZONE' ? `${row.code} ${row.name}` : locationDisplayName(row)}\n${label[state] || state} · ${row.itemTypeCount || 0} 物料`} />; })}</Layer></Stage></DndContext>
  </div>;
}

function byUnit(rows: any[]) {
  const totals = new Map<string, { unit: string; onHandQty: number; availableQty: number; capacityQty: number; occupiedQty: number }>();
  rows.flatMap(row => row.items || []).forEach(item => { const unit = item.unit || '未设单位', next = totals.get(unit) || { unit, onHandQty: 0, availableQty: 0, capacityQty: 0, occupiedQty: 0 }; next.onHandQty += n(item.onHandQty); next.availableQty += n(item.availableQty); if (item.capacityQty !== null && item.capacityQty !== undefined) { next.capacityQty += n(item.capacityQty); next.occupiedQty += n(item.onHandQty) + n(item.pendingInboundQty); } totals.set(unit, next); });
  return [...totals.values()].map(row => ({ ...row, usageRate: row.capacityQty ? Math.round(row.occupiedQty / row.capacityQty * 1000) / 10 : null }));
}

export function WarehouseVirtualMapPage({ user }: { user?: User }) {
  const nav = useNavigate(), route = useLocation(), query = useMemo(() => new URLSearchParams(route.search), [route.search]);
  const [index, setIndex] = useState<any>({ warehouses: [], summary: {} }); const [data, setData] = useState<any>(); const [warehouseId, setWarehouseId] = useState<string>(); const [mode, setMode] = useState<Mode>('ZONE'); const [zoneId, setZoneId] = useState<string>(); const [locationId, setLocationId] = useState<string>(); const [materials, setMaterials] = useState<any[]>([]); const [stock, setStock] = useState<any[]>([]); const [drawer, setDrawer] = useState<any>(); const [layout, setLayout] = useState<any>(); const [nodes, setNodes] = useState<any[]>([]); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [view, setView] = useState<View>({ x: 0, y: 0, scale: 1 }); const [expandedMap, setExpandedMap] = useState(false); const [chartUnit, setChartUnit] = useState<string>(); const [hoveredLocation, setHoveredLocation] = useState<any>();
  const warehouses = index.warehouses || [], warehouse = warehouses.find((row: any) => row.id === warehouseId), zones = data?.zones || [], currentZone = zones.find((row: any) => row.id === zoneId), locations = data?.locations || [], currentLocation = locations.find((row: any) => row.locationId === locationId), scopedLocations = zoneId ? locations.filter((row: any) => row.zoneId === zoneId) : locations, selected = mode === 'ZONE' ? currentZone : currentLocation, detailLocations = mode === 'ZONE' ? currentZone?.locations || scopedLocations : currentLocation ? [currentLocation] : [], unitStats = byUnit(detailLocations), capacityStats = unitStats.filter(row => row.capacityQty > 0), usedLocationCount = detailLocations.filter(row => row.itemTypeCount > 0).length;
  const alerts = [...detailLocations.filter(row => ['LOW', 'WARNING', 'FULL', 'LOCKED'].includes(row.status || row.state)).map(row => ({ type: row.status || row.state, code: row.locationCode || row.code, text: label[row.status || row.state] || row.status || row.state })), ...(data?.recentDocuments || []).filter((row: any) => row.documentType === 'STOCK_CHECK' && row.status === 'SUBMITTED').map((row: any) => ({ type: 'STOCK_CHECK', code: row.documentNo, text: '待审批盘点' }))];
  const availableUnits = [...new Set(materials.map(row => row.unit || '未设单位'))], chartRows = topMaterialsByUnit(materials, chartUnit || availableUnits[0]);
  const mapRows = useMemo(() => { const source = mode === 'ZONE' ? zones : scopedLocations, saved = new Map(nodes.map((node: any) => [node.businessId, node])); return source.map((row: any) => ({ ...row, id: mode === 'ZONE' ? row.id : row.locationId, ...(saved.get(mode === 'ZONE' ? row.id : row.locationId) || {}) })); }, [mode, zones, scopedLocations, nodes]);
  const loadIndex = async () => { setLoading(true); try { const next = await api('/warehouses/storage-state'); setIndex(next); const wanted = next.warehouses?.find((row: any) => row.warehouseCode === query.get('warehouse')); setWarehouseId((old: any) => next.warehouses?.some((row: any) => row.id === old) ? old : wanted?.id || next.warehouses?.[0]?.id); } catch (reason: any) { setError(reason.message || '数据加载失败'); } finally { setLoading(false); } };
  const loadWorkspace = async (id: string) => { try { const [next, layouts] = await Promise.all([api(`/warehouses/${id}/workspace-state`), api(`/warehouses/${id}/layouts`)]); setData(next); const zone = next.zones?.find((row: any) => row.code === query.get('zone')) || next.zones?.[0], location = next.locations?.find((row: any) => row.locationCode === query.get('location')); setZoneId(zone?.id); setLocationId(location?.locationId); const active = layouts.find((row: any) => row.status === 'PUBLISHED') || layouts[0]; setLayout(active); setNodes(active ? await api(`/warehouses/${id}/layouts/${active.id}/nodes`) : []); setView({ x: 0, y: 0, scale: 1 }); } catch (reason: any) { setError(reason.message || '工作区加载失败'); } };
  useEffect(() => { void loadIndex(); }, []); useEffect(() => { if (warehouseId) void loadWorkspace(warehouseId); }, [warehouseId]); useEffect(() => { if (!warehouseId) return; if (mode === 'ZONE' && zoneId) api(`/warehouses/${warehouseId}/areas/${zoneId}/material-summary`).then((result: any) => setMaterials(result.materials || [])).catch((reason: any) => setError(reason.message)); if (mode === 'LOCATION' && locationId) api(`/warehouses/${warehouseId}/locations/${locationId}/stock`).then(setStock).catch((reason: any) => setError(reason.message)); }, [warehouseId, mode, zoneId, locationId]); useEffect(() => { if (availableUnits.length && !availableUnits.includes(chartUnit || '')) setChartUnit(availableUnits[0]); }, [availableUnits.join('|')]);
  const pick = (id: string) => { if (id === '__expand__') return setExpandedMap(true); if (mode === 'ZONE') { setZoneId(id); setLocationId(undefined); } else setLocationId(id); };
  const move = (id: string, point: any) => setNodes(old => old.some(row => row.businessId === id) ? old.map(row => row.businessId === id ? { ...row, ...point } : row) : [...old, { businessId: id, ...point }]);
  const save = async () => { if (!warehouseId) return; try { let active = layout; if (!active) { active = await api(`/warehouses/${warehouseId}/layouts`, { method: 'POST', body: JSON.stringify({ layoutName: '默认二维布局', layoutType: '2D' }) }); setLayout(active); } const saved = new Map(nodes.map((node: any) => [node.businessId, node])), layoutRows = [...grid(zones).map((row: any) => ({ ...row, ...(saved.get(row.id) || {}), nodeType: 'ZONE', businessId: row.id })), ...grid(locations).map((row: any) => ({ ...row, ...(saved.get(row.locationId) || {}), nodeType: 'LOCATION', businessId: row.locationId }))]; await api(`/warehouses/${warehouseId}/layouts/${active.id}/nodes`, { method: 'PUT', body: JSON.stringify({ nodes: layoutRows.map((row: any) => ({ nodeType: row.nodeType, businessId: row.businessId, code: row.code || row.locationCode, name: row.name || row.locationName, x: row.x, y: row.y, width: row.width, height: row.height, layer: row.nodeType === 'ZONE' ? 1 : 2 })) }) }); await api(`/warehouses/${warehouseId}/layouts/${active.id}/publish`, { method: 'POST' }); message.success('布局已保存'); setEditing(false); await loadWorkspace(warehouseId); } catch (reason: any) { message.error(reason.message || '保存失败'); } };
  const contextPath = (path: string, extra: Record<string, string> = {}) => { if (!warehouse) return; const params = new URLSearchParams(extra); params.set('warehouse', warehouse.warehouseCode); if (currentZone) params.set('zone', currentZone.code); if (mode === 'LOCATION' && currentLocation) params.set('location', currentLocation.locationCode); nav(`${path}${path.includes('?') ? '&' : '?'}${params}`); };
  const goOperation = (operation: Operation) => { if (!warehouse) return; if (warehouse.warehouseType === 'DEFECTIVE') return nav('/approvals?businessType=DEFECTIVE'); if (operation === 'outbound' && warehouse.warehouseType === 'RAW') return nav('/production/tasks'); contextPath('/inventory/warehouse-management', { operation }); };
  const drill = async (item: any) => { if (!warehouseId || !zoneId) return; setDrawer({ item, rows: [] }); try { setDrawer({ item, rows: await api(`/warehouses/${warehouseId}/areas/${zoneId}/materials/${item.materialId}/distribution`) }); } catch (reason: any) { setDrawer({ item, rows: [], error: reason.message }); } };
  const state = selected?.state || selected?.status || 'EMPTY'; const details = selected ? [{ key: 'warehouse', label: '所属仓库', children: `${warehouse?.name || '—'}（${warehouse?.warehouseCode || '—'}）` }, { key: 'zone', label: '当前库区', children: currentZone ? `${currentZone.name}（${currentZone.code}）` : '—' }, ...(mode === 'LOCATION' ? [{ key: 'location', label: '当前库位', children: <LocationName location={currentLocation} /> }] : []), { key: 'state', label: '状态', children: <Tag color={color[state]}>{label[state] || state}</Tag> }] : [];
  const actionButtons = warehouse?.warehouseType === 'DEFECTIVE' ? [{ text: '不良品处理', permission: 'inventory.view', primary: true, action: () => goOperation('inbound') }] : [{ text: '入库', permission: 'stock.create', primary: true, action: () => goOperation('inbound') }, { text: warehouse?.warehouseType === 'RAW' ? '生产领料' : '出库', permission: 'stock.create', action: () => goOperation('outbound') }, { text: '移库', permission: 'stock.move', action: () => goOperation('move') }, { text: '盘点', permission: 'stock.count', action: () => goOperation('count') }].filter(item => can(user, item.permission)); const recentTransactions = limitRecentRecords(data?.recentTransactions || []);
  return <PageScaffold bare title="虚拟仓库" subtitle="实时查看有权限仓库的库区、库位、库存和容量状态。" extra={<Space><Button icon={<ReloadOutlined />} loading={loading} onClick={() => { void loadIndex(); if (warehouseId) void loadWorkspace(warehouseId); }}>刷新</Button>{can(user, 'warehouse.layout.edit') && <Button icon={editing ? <SaveOutlined /> : <EditOutlined />} type={editing ? 'primary' : 'default'} onClick={() => editing ? void save() : setEditing(true)}>{editing ? '保存布局' : '编辑仓库布局'}</Button>}</Space>}>
    {error && <Alert type="warning" showIcon closable message={error} className="virtual-error" onClose={() => setError('')} />}<div className="virtual-dashboard virtual-dashboard-compact">
      <section className="virtual-metrics virtual-metrics-compact">{[['可查看仓库', n(index.summary?.warehouseCount), DatabaseOutlined, 'blue'], ['库区 / 库位', `${n(index.summary?.zoneCount)} / ${n(index.summary?.locationCount)}`, ApartmentOutlined, 'blue'], ['物料种类', n(index.summary?.itemTypeCount), DatabaseOutlined, 'blue'], ['库存预警', `低库存 ${n(index.summary?.lowStockCount)} · 满库库位 ${n(index.summary?.fullLocationCount)}`, DatabaseOutlined, 'warning']].map(([name, value, Icon, tone]: any) => <Card key={name} className={`virtual-metric virtual-metric-${tone}`}><span className="virtual-metric-icon"><Icon /></span><div><small>{name}</small><strong>{value}</strong></div></Card>)}</section>
      <Card className="virtual-overview-card" title="仓库范围"><div className="virtual-warehouse-cards">{warehouses.map((row: any) => <button type="button" key={row.id} className={row.id === warehouseId ? 'is-selected' : ''} onClick={() => setWarehouseId(row.id)}><b>{row.name} <small>{row.warehouseCode}</small>{row.id === warehouseId && <Tag color="blue">已选</Tag>}</b><span>库区 {row.zones?.length || 0} · 库位 {row.locationCount || 0} · 物料 {row.itemTypeCount || 0}</span></button>)}</div></Card>
      {warehouse && <div className="virtual-workspace"><section className="virtual-left-column"><Card className="virtual-map-panel" title="二维仓储地图" extra={<Segmented size="small" value={mode} options={[{ value: 'ZONE', label: '库区视图' }, { value: 'LOCATION', label: '库位视图' }]} onChange={value => { setMode(value as Mode); if (value === 'ZONE') setLocationId(undefined); }} />}><div className="virtual-map-context"><strong>{warehouse.name} · {warehouse.warehouseCode}</strong><span>{editing ? '编辑模式：拖动节点后保存' : '点击节点查看详情；展开地图可查看完整布局'}</span></div><Canvas rows={mapRows} selected={mode === 'ZONE' ? zoneId : locationId} mode={mode} editing={editing} pick={pick} move={move} view={view} setView={setView} onHover={setHoveredLocation} />{locationActualPosition(hoveredLocation) && <span className="virtual-map-location-tooltip">实际位置：{locationActualPosition(hoveredLocation)}</span>}<div className="virtual-legend">{Object.entries(color).map(([key, value]) => <span key={key}><i style={{ background: value }} />{label[key]}</span>)}</div></Card></section>
        <aside className="virtual-right-column"><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .18 }}><Card className="virtual-detail-panel" title={mode === 'ZONE' ? '库区详情' : '库位详情'}><Descriptions column={1} size="small" items={details} /><div className="virtual-detail-summary"><span><small>物料种类</small><strong>{selected?.itemTypeCount || 0}</strong></span><span><small>库位总数</small><strong>{detailLocations.length}</strong></span><span><small>已用库位</small><strong>{usedLocationCount}</strong></span><span><small>空库位</small><strong>{Math.max(0, detailLocations.length - usedLocationCount)}</strong></span></div></Card><Card className="virtual-stats-panel" title="按单位统计"><div className="virtual-detail-stats">{unitStats.length ? unitStats.map(row => <span key={row.unit}><small>{row.unit} · 可用 {formatQuantity(row.availableQty)}</small><strong>{formatQuantity(row.onHandQty)}</strong>{row.capacityQty > 0 ? <em>容量利用率 {row.usageRate}%</em> : <em>容量不限量</em>}</span>) : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无库存" />}</div>{capacityStats.length > 0 && <small className="virtual-capacity-note">容量利用率按单位独立计算</small>}</Card><Card className="virtual-actions-panel" title="快捷作业"><div className="virtual-detail-actions">{actionButtons.map((item: any) => <Button key={item.text} type={item.primary ? 'primary' : 'default'} icon={item.text === '入库' ? <InboxOutlined /> : item.text === '移库' ? <SwapOutlined /> : undefined} onClick={item.action}>{item.text}</Button>)}</div><div className="virtual-secondary-actions"><Button type="link" onClick={() => contextPath('/inventory/warehouse-management')}>查看详情</Button><Button type="link" onClick={() => contextPath('/inventory/management?tab=reports')}>查看库存</Button><Button type="link" onClick={() => contextPath('/inventory/management?tab=flows')}>查看流水</Button></div></Card></motion.div></aside></div>}
      {warehouse && <section className="virtual-insight-grid"><Card title="库区库存分析" className="virtual-stock-panel" extra={availableUnits.length > 1 ? <Segmented size="small" value={chartUnit || availableUnits[0]} options={availableUnits} onChange={value => setChartUnit(String(value))} /> : <span className="virtual-card-hint">{availableUnits[0] || '—'} · Top 10</span>}><HorizontalChart rows={chartRows} onPick={drill} /></Card><Card title="库存预警与待处理" className="virtual-alert-panel">{alerts.length ? <div className="virtual-alert-list">{alerts.slice(0, 5).map((item, itemIndex) => <div key={`${item.type}-${item.code}-${itemIndex}`}><i style={{ background: color[item.type] || '#fa8c16' }} /><strong>{label[item.type] || item.text}</strong><span>{item.code} · {item.text}</span></div>)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前无预警与待处理事项" />}</Card></section>}
      <Card className="virtual-recent-tabs" title="最近记录" extra={<Button type="link" onClick={() => contextPath('/inventory/management?tab=flows')}>查看全部</Button>}><Tabs size="small" items={[{ key: 'flows', label: '最近库存流水', children: <Table size="small" rowKey="id" pagination={false} dataSource={recentTransactions} columns={[{ title: '时间', dataIndex: 'createdAt', render: formatBeijingTime }, { title: '物料', render: (_: any, row: any) => `${row.itemCode} ${row.itemName}` }, { title: '库位', render: (_: any, row: any) => <LocationName location={row} /> }, { title: '数量', dataIndex: 'deltaQty', align: 'right', render: (value: any) => <span className={n(value) >= 0 ? 'virtual-quantity-in' : 'virtual-quantity-out'}>{n(value) > 0 ? '+' : ''}{formatQuantity(value)}</span> }, { title: '操作类型', dataIndex: 'documentType', render: (value: string) => label[value] || '库存变更' }, { title: '操作人', dataIndex: 'operator', render: show }] } /> }, { key: 'docs', label: '最近单据', children: <Table size="small" rowKey="id" pagination={false} dataSource={limitRecentRecords(data?.recentDocuments || [])} columns={[{ title: '单据编号', dataIndex: 'documentNo' }, { title: '单据类型', dataIndex: 'documentType', render: (value: string) => label[value] || value }, { title: '状态', dataIndex: 'status', render: (value: string) => label[value] || value }, { title: '时间', dataIndex: 'createdAt', render: formatBeijingTime }] } /> }]} /></Card>
    </div>
    <Drawer width={720} open={Boolean(drawer)} title={drawer ? `${drawer.item.materialCode} ${drawer.item.materialName} · 库区库存分布` : ''} onClose={() => setDrawer(undefined)}><Table size="small" rowKey={(row: any) => `${row.locationId}-${row.batchNo || ''}`} dataSource={drawer?.rows || []} pagination={false} locale={{ emptyText: drawer?.error || '暂无库存分布' }} columns={[{ title: '库位', render: (_: any, row: any) => <LocationName location={row} /> }, { title: '批次', dataIndex: 'batchNo', render: show }, { title: '可用', dataIndex: 'availableQty', render: formatQuantity }, { title: '锁定', dataIndex: 'lockedQty', render: formatQuantity }, { title: '现存', dataIndex: 'totalQty', render: formatQuantity }]} /></Drawer>
    <Modal open={expandedMap} title={`二维仓储地图 · ${warehouse?.name || ''}`} width="calc(100vw - 48px)" style={{ top: 24 }} footer={null} onCancel={() => setExpandedMap(false)}><Canvas rows={mapRows} selected={mode === 'ZONE' ? zoneId : locationId} mode={mode} editing={editing} pick={(id: string) => id === '__expand__' ? undefined : pick(id)} move={move} view={view} setView={setView} fullscreen /><div className="virtual-legend">{Object.entries(color).map(([key, value]) => <span key={key}><i style={{ background: value }} />{label[key]}</span>)}</div></Modal>
  </PageScaffold>;
}
