import { useEffect, useMemo, useRef, useState } from 'react';
import * as echarts from 'echarts';
import { DndContext } from '@dnd-kit/core';
import { Layer, Rect, Stage, Text } from 'react-konva';
import { motion } from 'motion/react';
import { Alert, Button, Card, Descriptions, Drawer, Empty, Segmented, Space, Table, Tabs, Tag, message } from 'antd';
import { ApartmentOutlined, CompressOutlined, DatabaseOutlined, EditOutlined, ReloadOutlined, SaveOutlined } from '@ant-design/icons';
import { useLocation, useNavigate } from 'react-router-dom';
import { api } from './api';
import { PageScaffold } from './components';
import { formatBeijingTime, formatQuantity } from './domain';

type User = { role?: string; permissions?: string[] }; type Mode = 'ZONE' | 'LOCATION';
const label: Record<string, string> = { DISABLED: '已停用', FULL: '满库', LOCKED: '库存锁定', WARNING: '容量预警', LOW: '低库存', NORMAL: '正常', EMPTY: '空库位', ACTIVE: '启用', MATERIAL_INBOUND: '原材料入库', FINISHED_INBOUND: '成品入库', FINISHED_OUTBOUND: '成品出库', STOCK_MOVE: '移库', DRAFT: '草稿', SUBMITTED: '待审核', POSTED: '已过账' };
const color: Record<string, string> = { DISABLED: '#d7dce3', FULL: '#ff7875', LOCKED: '#b37feb', WARNING: '#ffc53d', LOW: '#ffd666', NORMAL: '#73d13d', EMPTY: '#91caff' };
const n = (v: any) => Number(v || 0); const show = (v: any, fallback = '—') => String(v || '').trim() || fallback; const can = (u: User | undefined, p: string) => u?.role === 'ADMIN' || Boolean(u?.permissions?.includes(p));
const grid = (rows: any[]) => { const cols = Math.max(1, Math.ceil(Math.sqrt(Math.max(1, rows.length)))); return rows.map((row, i) => ({ ...row, x: row.x ?? 32 + (i % cols) * 168, y: row.y ?? 32 + Math.floor(i / cols) * 106, width: row.width ?? 146, height: row.height ?? 78 })); };

function Chart({ rows, onPick }: { rows: any[]; onPick: (row: any) => void }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { if (!ref.current || !rows.length) return; const c = echarts.init(ref.current), units = [...new Set(rows.map(row => row.unit || '未设单位'))]; c.setOption({ animationDuration: 200, grid: { left: 55, right: 36, top: 30, bottom: 78 }, legend: { data: units }, tooltip: { trigger: 'axis' }, dataZoom: [{ type: 'inside' }, { type: 'slider', height: 14, bottom: 18 }], xAxis: { type: 'category', data: rows.map(row => row.materialCode), axisLabel: { rotate: 32 } }, yAxis: units.map((unit, i) => ({ type: 'value', name: unit, position: i ? 'right' : 'left', minInterval: 1 })), series: units.map((unit, i) => ({ name: unit, type: 'bar', yAxisIndex: i, data: rows.map(row => row.unit === unit ? n(row.quantity) : null), itemStyle: { color: ['#1677ff', '#13c2c2', '#722ed1'][i % 3], borderRadius: [4, 4, 0, 0] } })) }); c.on('click', (e: any) => rows[e.dataIndex] && onPick(rows[e.dataIndex])); const observer = new ResizeObserver(() => c.resize()); observer.observe(ref.current); return () => { observer.disconnect(); c.dispose(); }; }, [rows, onPick]); return rows.length ? <div className="virtual-unit-chart" ref={ref} /> : <Empty description="当前库区暂无库存物料" />; }

function Canvas({ rows, selected, mode, editing, pick, move }: any) { const host = useRef<HTMLDivElement>(null), [size, setSize] = useState({ width: 700, height: 370 }), [view, setView] = useState({ x: 0, y: 0, scale: 1 }); useEffect(() => { const update = () => setSize({ width: host.current?.clientWidth || 700, height: host.current?.clientHeight || 370 }); update(); const watcher = new ResizeObserver(update); if (host.current) watcher.observe(host.current); return () => watcher.disconnect(); }, []); const nodes = grid(rows); return <div className="virtual-konva-wrap" ref={host}><div className="virtual-canvas-tools"><Button size="small" icon={<CompressOutlined />} onClick={() => setView({ x: 0, y: 0, scale: 1 })}>适配</Button></div><DndContext><Stage width={size.width} height={size.height} draggable={!editing} x={view.x} y={view.y} scaleX={view.scale} scaleY={view.scale} onWheel={(e: any) => { e.evt.preventDefault(); setView(value => ({ ...value, scale: Math.max(.55, Math.min(1.7, value.scale * (e.evt.deltaY > 0 ? .92 : 1.08))) })); }}><Layer>{nodes.map((row: any) => { const id = row.id || row.locationId, state = row.state || row.status || 'EMPTY', active = id === selected; return <Rect key={id} x={row.x} y={row.y} width={row.width} height={row.height} cornerRadius={9} fill={active ? '#e6f4ff' : '#fff'} stroke={color[state] || color.EMPTY} strokeWidth={active ? 3 : 1.4} shadowBlur={active ? 6 : 2} shadowOpacity={.12} draggable={editing} onClick={() => pick(id)} onTap={() => pick(id)} onDblClick={() => pick(id)} onDragEnd={(e: any) => move(id, { x: e.target.x(), y: e.target.y() })} />; })}{nodes.map((row: any) => { const state = row.state || row.status || 'EMPTY'; return <Text key={`text-${row.id || row.locationId}`} x={row.x + 10} y={row.y + 10} width={row.width - 20} fontSize={12} fontFamily="Microsoft YaHei" lineHeight={1.55} fill="#23324a" listening={false} text={`${mode === 'ZONE' ? `${row.code} ${row.name}` : `${row.locationCode} ${row.locationName}`}\n${label[state] || state} · ${row.itemTypeCount || 0} 物料`} />; })}</Layer></Stage></DndContext></div>; }

export function WarehouseVirtualMapPage({ user }: { user?: User }) {
  const nav = useNavigate(), currentRoute = useLocation(), query = useMemo(() => new URLSearchParams(currentRoute.search), [currentRoute.search]); const [index, setIndex] = useState<any>({ warehouses: [], summary: {} }); const [data, setData] = useState<any>(); const [warehouseId, setWarehouseId] = useState<string>(); const [mode, setMode] = useState<Mode>('ZONE'); const [zoneId, setZoneId] = useState<string>(); const [locationId, setLocationId] = useState<string>(); const [materials, setMaterials] = useState<any[]>([]); const [stock, setStock] = useState<any[]>([]); const [drawer, setDrawer] = useState<any>(); const [layout, setLayout] = useState<any>(); const [nodes, setNodes] = useState<any[]>([]); const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const warehouses = index.warehouses || [], warehouse = warehouses.find((row: any) => row.id === warehouseId), zones = data?.zones || [], currentZone = zones.find((row: any) => row.id === zoneId), locations = data?.locations || [], currentLocation = locations.find((row: any) => row.locationId === locationId), scopedLocations = zoneId ? locations.filter((row: any) => row.zoneId === zoneId) : locations, selected = mode === 'ZONE' ? currentZone : currentLocation;
  const loadIndex = async () => { setLoading(true); try { const next = await api('/warehouses/storage-state'); setIndex(next); const wanted = next.warehouses?.find((row: any) => row.warehouseCode === query.get('warehouse')); setWarehouseId((old: any) => next.warehouses?.some((row: any) => row.id === old) ? old : wanted?.id || next.warehouses?.[0]?.id); } catch (e: any) { setError(e.message || '数据加载失败'); } finally { setLoading(false); } };
  const loadWorkspace = async (id: string) => { try { const [next, layouts] = await Promise.all([api(`/warehouses/${id}/workspace-state`), api(`/warehouses/${id}/layouts`)]); setData(next); const z = next.zones?.find((row: any) => row.code === query.get('zone')) || next.zones?.[0]; const l = next.locations?.find((row: any) => row.locationCode === query.get('location')); setZoneId(z?.id); setLocationId(l?.locationId); const active = layouts.find((row: any) => row.status === 'PUBLISHED') || layouts[0]; setLayout(active); setNodes(active ? await api(`/warehouses/${id}/layouts/${active.id}/nodes`) : []); } catch (e: any) { setError(e.message || '工作区加载失败'); } };
  useEffect(() => { void loadIndex(); }, []); useEffect(() => { if (warehouseId) void loadWorkspace(warehouseId); }, [warehouseId]); useEffect(() => { if (!warehouseId) return; if (mode === 'ZONE' && zoneId) api(`/warehouses/${warehouseId}/areas/${zoneId}/material-summary`).then((r: any) => setMaterials(r.materials || []) as any).catch((e: any) => setError(e.message)); if (mode === 'LOCATION' && locationId) api(`/warehouses/${warehouseId}/locations/${locationId}/stock`).then(setStock).catch((e: any) => setError(e.message)); }, [warehouseId, mode, zoneId, locationId]);
  const mapRows = useMemo(() => { const source = mode === 'ZONE' ? zones : scopedLocations, saved = new Map(nodes.map((node: any) => [node.businessId, node])); return source.map((row: any) => ({ ...row, id: mode === 'ZONE' ? row.id : row.locationId, ...(saved.get(mode === 'ZONE' ? row.id : row.locationId) || {}) })); }, [mode, zones, scopedLocations, nodes]);
  const pick = (id: string) => mode === 'ZONE' ? (setZoneId(id), setLocationId(undefined)) : setLocationId(id); const move = (id: string, point: any) => setNodes(old => old.some((row: any) => row.businessId === id) ? old.map((row: any) => row.businessId === id ? { ...row, ...point } : row) : [...old, { businessId: id, ...point }]);
  const save = async () => { if (!warehouseId) return; try { let active = layout; if (!active) { active = await api(`/warehouses/${warehouseId}/layouts`, { method: 'POST', body: JSON.stringify({ layoutName: '默认二维布局', layoutType: '2D' }) }); setLayout(active); } const saved = new Map(nodes.map((node: any) => [node.businessId, node])); const layoutRows = [...grid(zones).map((row: any) => ({ ...row, ...(saved.get(row.id) || {}), nodeType: 'ZONE', businessId: row.id })), ...grid(locations).map((row: any) => ({ ...row, ...(saved.get(row.locationId) || {}), nodeType: 'LOCATION', businessId: row.locationId }))]; await api(`/warehouses/${warehouseId}/layouts/${active.id}/nodes`, { method: 'PUT', body: JSON.stringify({ nodes: layoutRows.map((row: any) => ({ nodeType: row.nodeType, businessId: row.businessId, code: row.code || row.locationCode, name: row.name || row.locationName, x: row.x, y: row.y, width: row.width, height: row.height, layer: row.nodeType === 'ZONE' ? 1 : 2 })) }) }); await api(`/warehouses/${warehouseId}/layouts/${active.id}/publish`, { method: 'POST' }); message.success('布局已保存'); setEditing(false); await loadWorkspace(warehouseId); } catch (e: any) { message.error(e.message || '保存失败'); } };
  const open = (path: string) => { if (!warehouse) return; const p = new URLSearchParams({ warehouseId: warehouse.id, warehouse: warehouse.warehouseCode }); if (currentZone) { p.set('zoneId', currentZone.id); p.set('zone', currentZone.code); } if (currentLocation) { p.set('locationId', currentLocation.locationId); p.set('location', currentLocation.locationCode); } nav(`${path}${path.includes('?') ? '&' : '?'}${p}`); };
  const drill = async (item: any) => { if (!warehouseId || !zoneId) return; setDrawer({ item, rows: [] }); try { setDrawer({ item, rows: await api(`/warehouses/${warehouseId}/areas/${zoneId}/materials/${item.materialId}/distribution`) }); } catch (e: any) { setDrawer({ item, rows: [], error: e.message }); } };
  const state = selected?.state || selected?.status || 'EMPTY'; const details = selected ? [{ key: 'warehouse', label: '仓库', children: `${warehouse?.name || '—'} (${warehouse?.warehouseCode || '—'})` }, { key: 'zone', label: '库区', children: currentZone ? `${currentZone.name} (${currentZone.code})` : '—' }, { key: 'node', label: mode === 'ZONE' ? '当前库区' : '当前库位', children: mode === 'ZONE' ? `${selected.code} ${selected.name}` : `${selected.locationCode} ${selected.locationName}` }, { key: 'state', label: '状态', children: <Tag color={color[state]}>{label[state] || state}</Tag> }, { key: 'items', label: '物料种类', children: selected.itemTypeCount || 0 }] : [];
  const actions = mode === 'ZONE' && currentZone ? [{ text: '查看库位', run: () => setMode('LOCATION') }, { text: '查看详细信息', run: () => open('/inventory/warehouse-management') }, { text: '查看库存', run: () => open('/inventory/management?tab=reports') }, { text: '查看流水', run: () => open('/inventory/management?tab=flows') }] : [{ text: '入库', primary: true, permission: 'stock.create', run: () => open(warehouse?.warehouseType === 'FG' ? '/finished-inbound' : '/inbound') }, { text: '出库', permission: 'stock.create', run: () => open('/outbound') }, { text: '移库', permission: 'stock.move', run: () => open('/moves') }, { text: '库存调整', permission: 'stock.adjust', run: () => open('/adjustments') }, { text: '查看流水', run: () => open('/inventory/management?tab=flows') }, { text: '查看详细信息', run: () => open('/inventory/warehouse-management') }, ...(mode === 'LOCATION' ? [{ text: '配置容量', run: () => open('/inventory/warehouse-management') }] : [])];
  return <PageScaffold bare title="虚拟仓库" subtitle="实时查看有权限仓库的库区、库位、库存和容量状态。" extra={<Space><Button icon={<ReloadOutlined />} loading={loading} onClick={() => { void loadIndex(); if (warehouseId) void loadWorkspace(warehouseId); }}>刷新</Button>{can(user, 'warehouse.layout.edit') && <Button icon={editing ? <SaveOutlined /> : <EditOutlined />} type={editing ? 'primary' : 'default'} onClick={() => editing ? void save() : setEditing(true)}>{editing ? '保存布局' : '编辑仓库布局'}</Button>}</Space>}>
    {error && <Alert type="warning" showIcon closable message={error} className="virtual-error" onClose={() => setError('')} />}<div className="virtual-dashboard"><section className="virtual-metrics">{[['可查看仓库', index.summary?.warehouseCount, DatabaseOutlined], ['库区', index.summary?.zoneCount, ApartmentOutlined], ['库位', index.summary?.locationCount, DatabaseOutlined], ['物料种类', index.summary?.itemTypeCount, DatabaseOutlined], ['低库存', index.summary?.lowStockCount, DatabaseOutlined], ['满库库位', index.summary?.fullLocationCount, DatabaseOutlined]].map(([name, value, Icon]: any) => <Card key={name} className="virtual-metric"><span className="virtual-metric-icon"><Icon /></span><div><small>{name}</small><strong>{n(value)}</strong></div></Card>)}</section>
      <Card className="virtual-overview-card" title="仓库范围"><div className="virtual-warehouse-cards">{warehouses.map((row: any) => <button type="button" key={row.id} className={row.id === warehouseId ? 'is-selected' : ''} onClick={() => setWarehouseId(row.id)}><b>{row.name} <small>{row.warehouseCode}</small></b><span>库区 {row.zones?.length || 0} · 库位 {row.locationCount || 0} · 物料 {row.itemTypeCount || 0}</span></button>)}</div></Card>
      {warehouse && <div className="virtual-workspace"><section className="virtual-left-column"><Card className="virtual-map-panel" title="二维仓储地图" extra={<Segmented value={mode} options={[{ value: 'ZONE', label: '库区视图' }, { value: 'LOCATION', label: '库位视图' }]} onChange={value => { setMode(value as Mode); if (value === 'ZONE') setLocationId(undefined); }} />}><div className="virtual-map-context"><strong>{warehouse.name} · {warehouse.warehouseCode}</strong><span>{editing ? '编辑模式：拖动节点后保存' : '滚轮缩放，拖动画布平移，点击或双击节点聚焦'}</span></div><Canvas rows={mapRows} selected={mode === 'ZONE' ? zoneId : locationId} mode={mode} editing={editing} pick={pick} move={move} /><div className="virtual-legend">{Object.entries(color).map(([key, value]) => <span key={key}><i style={{ background: value }} />{label[key]}</span>)}</div></Card><Card className="virtual-stock-panel" title={mode === 'ZONE' ? '库区库存分析（按单位）' : '库位库存与批次明细'}>{mode === 'ZONE' ? currentZone ? <Chart rows={materials} onPick={drill} /> : <Empty description="请选择库区" /> : currentLocation ? <Table size="small" rowKey={(row: any) => `${row.itemId}-${row.batchNo || ''}`} dataSource={stock} pagination={false} scroll={{ y: 280, x: 860 }} columns={[{ title: '物料', render: (_: any, row: any) => `${row.itemCode} ${row.itemName}` }, { title: '批次', dataIndex: 'batchNo', render: show }, { title: '可用', dataIndex: 'availableQty', align: 'right', render: formatQuantity }, { title: '锁定', dataIndex: 'lockedQty', align: 'right', render: formatQuantity }, { title: '现存', dataIndex: 'totalQty', align: 'right', render: formatQuantity }, { title: '容量', render: (_: any, row: any) => currentLocation.items?.find((item: any) => item.itemId === row.itemId)?.capacityQty || '不限量' }]} /> : <Empty description="请选择库位" />}</Card></section>
        <aside className="virtual-right-column"><motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .18 }}><Card className="virtual-detail-panel" title={mode === 'ZONE' ? '库区详情' : '库位详情'}><Descriptions column={1} size="small" items={details} /></Card><Card className="virtual-stats-panel" title="按单位统计"><div className="virtual-detail-stats">{(data?.unitStatistics || []).map((row: any) => <span key={row.unit}><small>{row.unit}</small><strong>{formatQuantity(row.onHandQty)}</strong><em>可用 {formatQuantity(row.availableQty)}</em></span>)}</div></Card><Card className="virtual-actions-panel" title="功能操作"><div className="virtual-detail-actions">{actions.map((action: any) => <Button key={action.text} type={action.primary ? 'primary' : 'default'} disabled={Boolean(action.permission && !can(user, action.permission))} onClick={action.run}>{action.text}</Button>)}</div></Card></motion.div></aside></div>}
      <Card className="virtual-recent-tabs" title="最近记录"><Tabs size="small" items={[{ key: 'flows', label: '最近库存流水', children: <Table size="small" rowKey="id" pagination={false} dataSource={data?.recentTransactions || []} columns={[{ title: '时间', dataIndex: 'createdAt', render: formatBeijingTime }, { title: '物料', render: (_: any, row: any) => `${row.itemCode} ${row.itemName}` }, { title: '库位', dataIndex: 'locationCode' }, { title: '数量', dataIndex: 'deltaQty', render: formatQuantity }]} /> }, { key: 'docs', label: '最近单据', children: <Table size="small" rowKey="id" pagination={false} dataSource={data?.recentDocuments || []} columns={[{ title: '单据编号', dataIndex: 'documentNo' }, { title: '单据类型', dataIndex: 'documentType', render: (value: string) => label[value] || value }, { title: '状态', dataIndex: 'status', render: (value: string) => label[value] || value }, { title: '时间', dataIndex: 'createdAt', render: formatBeijingTime }]} /> }]} /></Card></div>
    <Drawer width={720} open={Boolean(drawer)} title={drawer ? `${drawer.item.materialCode} ${drawer.item.materialName} · 库区库存分布` : ''} onClose={() => setDrawer(undefined)}><Table size="small" rowKey={(row: any) => `${row.locationId}-${row.batchNo || ''}`} dataSource={drawer?.rows || []} pagination={false} locale={{ emptyText: drawer?.error || '暂无库存分布' }} columns={[{ title: '库位', render: (_: any, row: any) => `${row.locationCode} ${row.locationName}` }, { title: '批次', dataIndex: 'batchNo', render: show }, { title: '可用', dataIndex: 'availableQty', render: formatQuantity }, { title: '锁定', dataIndex: 'lockedQty', render: formatQuantity }, { title: '现存', dataIndex: 'totalQty', render: formatQuantity }]} /></Drawer>
  </PageScaffold>;
}
