import { Body, Controller, Delete, Get, HttpStatus, Param, Patch, Post, Put, Query } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { DataSource, QueryRunner } from 'typeorm';
import { randomUUID } from 'crypto';
import { CurrentUser, Permissions } from '../auth/auth.decorators';
import { AuthUser } from '../common/constants';
import { snapshotUser } from '../common/snapshot';
import { BusinessException } from '../common/business.exception';

@ApiTags('仓库')
@Controller('warehouses')
export class WarehousesController {
  constructor(private readonly db: DataSource) {}

  @Get()
  @Permissions('master.view')
  async list() {
    return this.db.query(
      `SELECT w.id,w.warehouse_code "warehouseCode",w.display_name "displayName",w.name,w.warehouse_type "warehouseType",w.status,
        (SELECT count(*) FROM warehouse_zones z WHERE z.warehouse_id=w.id AND z.deleted_at IS NULL)::int "zoneCount"
       FROM warehouses w WHERE w.deleted_at IS NULL ORDER BY w.warehouse_code`
    );
  }

  @Get('virtual-overview')
  @Permissions('warehouse.virtual.view')
  async virtualOverviewEndpoint() {
    return this.virtualOverviewData();
  }

  @Get(':id')
  @Permissions('warehouse.virtual.view')
  async get(@Param('id') id: string) {
    const [warehouse] = await this.db.query(
      `SELECT id,warehouse_code "warehouseCode",display_name "displayName",name,
        warehouse_type "warehouseType",status,created_at "createdAt",updated_at "updatedAt"
       FROM warehouses WHERE id=$1 AND deleted_at IS NULL`,
      [id],
    );
    if (!warehouse) throw new BusinessException('NOT_FOUND', '仓库不存在', HttpStatus.NOT_FOUND);
    const [zones, locations, summary, recentTransactions, recentDocuments] = await Promise.all([
      this.db.query(`SELECT z.id,z.sequence_no "sequenceNo",z.code,z.name,z.actual_location "actualLocation",z.location_count "locationCount",z.status,
        count(DISTINCT l.id) FILTER(WHERE l.status='ACTIVE' AND l.is_archived=false)::int "activeLocationCount",
        count(DISTINCT l.id) FILTER(WHERE l.is_archived=false)::int "locationCountActual",
        count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
        count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
        count(*) FILTER(WHERE sb.on_hand_qty=0)::int "zeroStockCount",max(sb.updated_at) "lastInventoryAt"
        FROM warehouse_zones z LEFT JOIN warehouse_locations l ON l.zone_id=z.id AND l.is_archived=false
        LEFT JOIN stock_balances sb ON sb.location_id=l.id LEFT JOIN items i ON i.id=sb.item_id
        WHERE z.warehouse_id=$1 AND z.deleted_at IS NULL GROUP BY z.id ORDER BY z.sequence_no`, [id]),
      this.db.query(`SELECT l.id,l.zone_id "zoneId",l.code,l.name,l.status,l.sort_order "sortOrder",l.system_default "systemDefault",
        l.auto_generated "autoGenerated",l.is_archived "isArchived",l.position_desc "positionDesc",
        count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
        coalesce(sum(sb.on_hand_qty),0)::text "onHandQty"
        FROM warehouse_locations l LEFT JOIN stock_balances sb ON sb.location_id=l.id
        WHERE l.warehouse_id=$1 GROUP BY l.id ORDER BY l.zone_id,l.sort_order NULLS LAST,l.code`, [id]),
      this.db.query(`SELECT count(DISTINCT z.id) FILTER(WHERE z.status='ACTIVE' AND z.deleted_at IS NULL)::int "zoneCount",
        count(DISTINCT l.id) FILTER(WHERE l.status='ACTIVE' AND l.is_archived=false)::int "locationCount",
        count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
        count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
        count(*) FILTER(WHERE sb.on_hand_qty=0)::int "zeroStockCount"
        FROM warehouses w LEFT JOIN warehouse_zones z ON z.warehouse_id=w.id AND z.deleted_at IS NULL
        LEFT JOIN warehouse_locations l ON l.zone_id=z.id AND l.is_archived=false LEFT JOIN stock_balances sb ON sb.location_id=l.id
        LEFT JOIN items i ON i.id=sb.item_id WHERE w.id=$1 GROUP BY w.id`, [id]).then(rows => rows[0] || {}),
      this.db.query(`SELECT t.id,t.created_at "createdAt",t.delta_qty "deltaQty",t.balance_after "balanceAfter",i.item_code "itemCode",i.name "itemName",l.code "locationCode",u.username "operator"
        FROM stock_transactions t JOIN items i ON i.id=t.item_id JOIN warehouse_locations l ON l.id=t.location_id
        LEFT JOIN users u ON u.id=t.created_by WHERE t.warehouse_id=$1 ORDER BY t.created_at DESC LIMIT 5`, [id]),
      this.db.query(`SELECT id,document_no "documentNo",document_type "documentType",status,created_at "createdAt",posted_at "postedAt"
        FROM stock_documents WHERE warehouse_id=$1 ORDER BY created_at DESC LIMIT 5`, [id]),
    ]);
    warehouse.zones = zones.map((zone: any) => ({ ...zone, locations: locations.filter((location: any) => location.zoneId === zone.id) }));
    warehouse.locations = locations;
    warehouse.summary = summary;
    warehouse.recentTransactions = recentTransactions;
    warehouse.recentDocuments = recentDocuments;
    warehouse.references = (await this.db.query(`SELECT ((SELECT count(*) FROM stock_documents WHERE warehouse_id=$1)+(SELECT count(*) FROM stock_transactions WHERE warehouse_id=$1)+(SELECT count(*) FROM stock_balances WHERE warehouse_id=$1))::int "referenceCount"`, [id]))[0];
    return warehouse;
  }

  @Post()
  @Permissions('master.manage')
  async create(@Body() dto: any) {
    const code = this.normalizeWarehouseCode(dto.warehouseCode);
    const zones = this.validateZones(dto.zones);
    const qr = this.db.createQueryRunner();
    await qr.connect(); await qr.startTransaction();
    try {
      const id = randomUUID();
      await qr.query(
        `INSERT INTO warehouses(id,warehouse_code,display_name,name,warehouse_type,status)
         VALUES($1,$2,$3,$4,$5,$6)`,
        [id, code, dto.displayName || dto.name, dto.name, dto.warehouseType, dto.status || 'ACTIVE'],
      );
      for (const zone of zones) await this.createZone(qr, id, code, zone);
      await qr.commitTransaction();
      return this.get(id);
    } catch (error: any) {
      await qr.rollbackTransaction();
      if (error.code === '23505') throw new BusinessException('DUPLICATE_CODE', '仓库编码或库区序号已存在', HttpStatus.CONFLICT);
      throw error;
    } finally {
      await qr.release();
    }
  }

  @Patch(':id')
  @Permissions('master.manage')
  async update(@Param('id') id: string, @Body() dto: any) {
    const qr = this.db.createQueryRunner();
    await qr.connect(); await qr.startTransaction();
    try {
      const [current] = await qr.query(
        `SELECT * FROM warehouses WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,
        [id],
      );
      if (!current) throw new BusinessException('NOT_FOUND', '仓库不存在', HttpStatus.NOT_FOUND);
      const code = dto.warehouseCode === undefined
        ? current.warehouse_code
        : this.normalizeWarehouseCode(dto.warehouseCode);
      const warehouseType = dto.warehouseType || current.warehouse_type;
      if (warehouseType !== current.warehouse_type) {
        await this.validateWarehouseTypeChange(qr, id, warehouseType);
      }
      const zones = dto.zones === undefined ? undefined : this.validateZones(dto.zones);
      if (code !== current.warehouse_code || zones) {
        await qr.query(
          `UPDATE warehouse_zones SET code='__EDIT__'||replace(id::text,'-','')
           WHERE warehouse_id=$1 AND deleted_at IS NULL`,
          [id],
        );
      }
      await qr.query(
        `UPDATE warehouses SET warehouse_code=$1,name=$2,display_name=$3,warehouse_type=$4,
          status=$5,updated_at=now() WHERE id=$6`,
        [
          code,
          dto.name ?? current.name,
          dto.displayName ?? current.display_name,
          warehouseType,
          dto.status ?? current.status,
          id,
        ],
      );

      if (zones) {
        const existing: any[] = await qr.query(
          `SELECT * FROM warehouse_zones WHERE warehouse_id=$1 AND deleted_at IS NULL FOR UPDATE`,
          [id],
        );
        const desiredIds = new Set(zones.filter(zone => zone.id).map(zone => zone.id));
        for (const zone of existing) {
          if (!desiredIds.has(zone.id)) await this.removeZone(qr, zone);
        }
        for (const zone of zones) {
          if (zone.id) {
            if (!existing.some(row => row.id === zone.id)) {
              throw new BusinessException('VALIDATION_ERROR', '库区不属于当前仓库');
            }
            const zoneCode = this.zoneCode(code, zone.sequenceNo);
            await qr.query(
              `UPDATE warehouse_zones SET sequence_no=$1,code=$2,name=$3,actual_location=$4,location_count=$5,
                status=$6,updated_at=now() WHERE id=$7`,
              [zone.sequenceNo, zoneCode, zone.name, zone.actualLocation, zone.locationCount, zone.status, zone.id],
            );
            await this.syncAutoLocations(qr, id, zone.id, code, zone);
          } else {
            await this.createZone(qr, id, code, zone);
          }
        }
      } else if (code !== current.warehouse_code) {
        const rows = await qr.query(`SELECT id,sequence_no "sequenceNo",name,actual_location "actualLocation",location_count "locationCount",status FROM warehouse_zones WHERE warehouse_id=$1 AND deleted_at IS NULL`, [id]);
        for (const zone of rows) {
          const zoneCode = this.zoneCode(code, zone.sequenceNo);
          await qr.query(`UPDATE warehouse_zones SET code=$1,updated_at=now() WHERE id=$2`, [zoneCode, zone.id]);
          await this.syncAutoLocations(qr, id, zone.id, code, zone);
        }
      }
      await qr.commitTransaction();
      return this.get(id);
    } catch (error: any) {
      await qr.rollbackTransaction();
      if (error.code === '23505') throw new BusinessException('DUPLICATE_CODE', '仓库编码或库区序号已存在', HttpStatus.CONFLICT);
      throw error;
    } finally {
      await qr.release();
    }
  }

  @Delete(':id')
  @Permissions('master.delete')
  async remove(@Param('id') id: string) {
    const qr = this.db.createQueryRunner();
    await qr.connect(); await qr.startTransaction();
    try {
      const [warehouse] = await qr.query(
        `SELECT * FROM warehouses WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,
        [id],
      );
      if (!warehouse) throw new BusinessException('NOT_FOUND', '仓库不存在', HttpStatus.NOT_FOUND);
      const [{ count }] = await qr.query(
        `SELECT (
          (SELECT count(*) FROM stock_documents WHERE warehouse_id=$1)
          +(SELECT count(*) FROM stock_balances WHERE warehouse_id=$1)
          +(SELECT count(*) FROM stock_transactions WHERE warehouse_id=$1)
          +(SELECT count(*) FROM items WHERE default_warehouse_id=$1)
          +(SELECT count(*) FROM warehouse_layouts WHERE warehouse_id=$1)
        )::int count`,
        [id],
      );
      const archive = warehouse.warehouse_code === 'RAW' || warehouse.warehouse_code === 'FG' || count > 0;
      if (archive) {
        await qr.query(`UPDATE warehouses SET status='INACTIVE',deleted_at=now(),updated_at=now() WHERE id=$1`, [id]);
        await qr.query(`UPDATE warehouse_zones SET status='INACTIVE',deleted_at=COALESCE(deleted_at,now()),updated_at=now() WHERE warehouse_id=$1`, [id]);
        await qr.query(`UPDATE warehouse_locations SET status='INACTIVE',updated_at=now() WHERE warehouse_id=$1`, [id]);
      } else {
        await qr.query(`DELETE FROM warehouse_visual_nodes WHERE layout_id IN (SELECT id FROM warehouse_layouts WHERE warehouse_id=$1) OR business_id IN (SELECT id FROM warehouse_zones WHERE warehouse_id=$1) OR business_id IN (SELECT id FROM warehouse_locations WHERE warehouse_id=$1) OR business_id IN (SELECT id FROM warehouse_racks WHERE warehouse_id=$1)`, [id]);
        await qr.query(`DELETE FROM warehouse_layouts WHERE warehouse_id=$1`, [id]);
        await qr.query(`DELETE FROM warehouse_locations WHERE warehouse_id=$1`, [id]);
        await qr.query(`DELETE FROM warehouse_racks WHERE warehouse_id=$1`, [id]);
        await qr.query(`DELETE FROM warehouse_zones WHERE warehouse_id=$1`, [id]);
        await qr.query(`DELETE FROM warehouses WHERE id=$1`, [id]);
      }
      await qr.commitTransaction();
      return { id, deletionMode: archive ? 'ARCHIVED' : 'HARD' };
    } catch (error) {
      await qr.rollbackTransaction();
      throw error;
    } finally {
      await qr.release();
    }
  }

  private normalizeWarehouseCode(value: unknown) {
    const code = String(value || '').trim().toUpperCase();
    if (!/^[A-Z0-9][A-Z0-9-]{0,19}$/.test(code)) {
      throw new BusinessException('VALIDATION_ERROR', '仓库编码只能包含大写字母、数字和横线，最长 20 位');
    }
    return code;
  }

  private validateZones(input: any[]) {
    if (!Array.isArray(input) || !input.length) {
      throw new BusinessException('VALIDATION_ERROR', '仓库至少需要一个库区');
    }
    const zones = input.map(zone => ({
      id: zone.id || undefined,
      sequenceNo: Number(zone.sequenceNo),
      name: String(zone.name || '').trim(),
      actualLocation: String(zone.actualLocation || '').trim(),
      locationCount: Number(zone.locationCount),
      status: zone.status || 'ACTIVE',
    }));
    if (zones.some(zone => !Number.isInteger(zone.sequenceNo) || zone.sequenceNo < 1 || zone.sequenceNo > 99)) {
      throw new BusinessException('VALIDATION_ERROR', '库区序号必须是 1 至 99 的整数');
    }
    if (new Set(zones.map(zone => zone.sequenceNo)).size !== zones.length) {
      throw new BusinessException('VALIDATION_ERROR', '同一仓库的库区序号不能重复');
    }
    if (new Set(zones.map(zone => zone.name)).size !== zones.length) {
      throw new BusinessException('VALIDATION_ERROR', '同一仓库内不能存在重复的库区名称');
    }
    if (zones.some(zone => !zone.name || !zone.actualLocation)) {
      throw new BusinessException('VALIDATION_ERROR', '库区名称和实际位置不能为空');
    }
    if (zones.some(zone => !/^[\p{Script=Han}A-Za-z0-9-]+$/u.test(zone.name) || zone.name.length > 24)) {
      throw new BusinessException('VALIDATION_ERROR', '库区名称仅允许中文、字母、数字和短横线，最长 24 位');
    }
    if (zones.some(zone => !Number.isInteger(zone.locationCount) || zone.locationCount < 1 || zone.locationCount > 500)) {
      throw new BusinessException('VALIDATION_ERROR', '库位数量必须为 1 至 500 的整数');
    }
    if (!zones.some(zone => zone.status === 'ACTIVE')) {
      throw new BusinessException('VALIDATION_ERROR', '至少保留一个启用库区');
    }
    return zones;
  }

  private zoneCode(warehouseCode: string, sequenceNo: number) {
    return `${warehouseCode}${String(sequenceNo).padStart(2, '0')}`;
  }

  private locationCode(warehouseCode: string, zoneName: string, sortOrder: number) {
    const code = `${warehouseCode}-${zoneName}-${String(sortOrder).padStart(2, '0')}`;
    if (code.length > 50) throw new BusinessException('VALIDATION_ERROR', '仓库编码与库区名称组合过长，无法生成库位编码');
    return code;
  }

  private async createZone(qr: QueryRunner, warehouseId: string, warehouseCode: string, zone: any) {
    const zoneId = randomUUID();
    const code = this.zoneCode(warehouseCode, zone.sequenceNo);
    await qr.query(
      `INSERT INTO warehouse_zones(id,warehouse_id,sequence_no,code,name,actual_location,location_count,status)
       VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,
      [zoneId, warehouseId, zone.sequenceNo, code, zone.name, zone.actualLocation, zone.locationCount, zone.status],
    );
    await this.syncAutoLocations(qr, warehouseId, zoneId, warehouseCode, zone);
  }

  private async syncAutoLocations(qr: QueryRunner, warehouseId: string, zoneId: string, warehouseCode: string, zone: any) {
    const locations: any[] = await qr.query(
      `SELECT id,code,sort_order "sortOrder",status FROM warehouse_locations
       WHERE zone_id=$1 AND auto_generated=true AND is_archived=false FOR UPDATE`, [zoneId],
    );
    const bySort = new Map(locations.map(row => [Number(row.sortOrder), row]));
    for (let sortOrder = 1; sortOrder <= zone.locationCount; sortOrder += 1) {
      const code = this.locationCode(warehouseCode, zone.name, sortOrder);
      const current = bySort.get(sortOrder);
      if (!current) {
        await qr.query(
          `INSERT INTO warehouse_locations(id,warehouse_id,zone_id,code,name,status,sort_order,system_default,auto_generated,is_archived)
           VALUES($1,$2,$3,$4,$4,$5,$6,false,true,false)`,
          [randomUUID(), warehouseId, zoneId, code, zone.status, sortOrder],
        );
      } else {
        const usage = await this.locationUsage(qr, current.id);
        const nextCode = usage.hasHistory ? current.code : code;
        await qr.query(`UPDATE warehouse_locations SET code=$1,name=$1,status=$2,updated_at=now() WHERE id=$3`, [nextCode, zone.status, current.id]);
      }
    }

    const excess = locations.filter(row => Number(row.sortOrder) > zone.locationCount);
    const blockers: string[] = [];
    for (const location of excess) {
      const usage = await this.locationUsage(qr, location.id);
      if (usage.onHandQty !== '0.0000' || usage.pendingDocuments.length) {
        blockers.push(`${location.code}${usage.onHandQty !== '0.0000' ? ` 当前库存${usage.onHandQty}` : ''}${usage.pendingDocuments.length ? ` 存在未完成单据 ${usage.pendingDocuments.join('、')}` : ''}`);
      }
    }
    if (blockers.length) throw new BusinessException('LOCATION_REDUCTION_BLOCKED', `无法减少库位数量：${blockers.join('；')}`);
    for (const location of excess) {
      const usage = await this.locationUsage(qr, location.id);
      if (usage.hasHistory) {
        await qr.query(`UPDATE warehouse_locations SET status='INACTIVE',is_archived=true,sort_order=NULL,updated_at=now() WHERE id=$1`, [location.id]);
      } else {
        await qr.query(`DELETE FROM warehouse_visual_nodes WHERE business_id=$1`, [location.id]);
        await qr.query(`DELETE FROM warehouse_locations WHERE id=$1`, [location.id]);
      }
    }
  }

  private async locationUsage(qr: QueryRunner, locationId: string) {
    const [summary] = await qr.query(`SELECT coalesce(sum(on_hand_qty),0)::text "onHandQty",count(*)::int "balanceRows" FROM stock_balances WHERE location_id=$1`, [locationId]);
    const pendingRows = await qr.query(`SELECT DISTINCT d.document_no "documentNo" FROM stock_documents d JOIN stock_document_lines l ON l.document_id=d.id WHERE d.status IN ('DRAFT','SUBMITTED') AND (l.location_id=$1 OR l.target_location_id=$1) ORDER BY d.document_no LIMIT 5`, [locationId]);
    const [history] = await qr.query(`SELECT ((SELECT count(*) FROM stock_transactions WHERE location_id=$1)+(SELECT count(*) FROM stock_document_lines WHERE location_id=$1 OR target_location_id=$1)+(SELECT count(*) FROM stock_document_receipt_allocations WHERE location_id=$1))::int "count"`, [locationId]);
    return { onHandQty: Number(summary?.onHandQty || 0).toFixed(0), pendingDocuments: pendingRows.map((row: any) => row.documentNo), hasHistory: Number(history?.count || 0) > 0 || Number(summary?.balanceRows || 0) > 0 };
  }

  private async removeZone(qr: QueryRunner, zone: any) {
    const [{ count }] = await qr.query(
      `SELECT (
        (SELECT count(*) FROM stock_document_lines WHERE location_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1) OR target_location_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1))
        +(SELECT count(*) FROM stock_balances WHERE location_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1))
        +(SELECT count(*) FROM stock_transactions WHERE location_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1))
        +(SELECT count(*) FROM stock_document_receipt_allocations WHERE location_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1))
        +(SELECT count(*) FROM warehouse_racks WHERE zone_id=$1)
      )::int count`,
      [zone.id],
    );
    if (count > 0) {
      await qr.query(`UPDATE warehouse_zones SET status='INACTIVE',deleted_at=now(),updated_at=now() WHERE id=$1`, [zone.id]);
      await qr.query(`UPDATE warehouse_locations SET status='INACTIVE',is_archived=true,sort_order=NULL,updated_at=now() WHERE zone_id=$1`, [zone.id]);
      return;
    }
    await qr.query(`DELETE FROM warehouse_visual_nodes WHERE business_id=$1 OR business_id IN (SELECT id FROM warehouse_locations WHERE zone_id=$1)`, [zone.id]);
    await qr.query(`DELETE FROM warehouse_locations WHERE zone_id=$1`, [zone.id]);
    await qr.query(`DELETE FROM warehouse_zones WHERE id=$1`, [zone.id]);
  }

  private async validateWarehouseTypeChange(qr: QueryRunner, warehouseId: string, targetType: string) {
    if (!['RAW', 'FG', 'DEFECTIVE'].includes(targetType)) {
      throw new BusinessException('VALIDATION_ERROR', '仓库类型只能是原材料库、成品库或不良品库');
    }
    const expectedTypes = targetType === 'DEFECTIVE' ? ['MATERIAL', 'FINISHED_GOOD'] : targetType === 'FG' ? ['FINISHED_GOOD'] : ['MATERIAL'];
    const conflicts = await qr.query(
      `SELECT i.item_code "itemCode",i.name,sum(sb.on_hand_qty)::text quantity
       FROM stock_balances sb JOIN items i ON i.id=sb.item_id
       WHERE sb.warehouse_id=$1 AND sb.on_hand_qty>0 AND NOT(i.item_type=ANY($2::varchar[]))
       GROUP BY i.id ORDER BY i.item_code`,
      [warehouseId, expectedTypes],
    );
    if (conflicts.length) {
      throw new BusinessException(
        'WAREHOUSE_TYPE_STOCK_CONFLICT',
        `仓库仍有与目标类型不兼容的库存：${conflicts.map((row: any) => `${row.itemCode}（${row.quantity}）`).join('、')}`,
        HttpStatus.CONFLICT,
        { conflicts },
      );
    }
  }

  private async virtualOverviewData() {
    const warehouses = await this.db.query(`SELECT w.id,w.warehouse_code "warehouseCode",w.display_name "displayName",w.name,w.warehouse_type "warehouseType",w.status,
      count(DISTINCT z.id) FILTER(WHERE z.status='ACTIVE' AND z.deleted_at IS NULL)::int "activeZoneCount",
      count(DISTINCT l.id) FILTER(WHERE l.status='ACTIVE' AND l.is_archived=false)::int "activeLocationCount",
      count(DISTINCT l.id)::int "locationCount",count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
      count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
      count(*) FILTER(WHERE sb.on_hand_qty=0)::int "zeroStockCount",max(sb.updated_at) "lastInventoryAt"
      FROM warehouses w LEFT JOIN warehouse_zones z ON z.warehouse_id=w.id AND z.deleted_at IS NULL
      LEFT JOIN warehouse_locations l ON l.zone_id=z.id AND l.is_archived=false LEFT JOIN stock_balances sb ON sb.location_id=l.id
      LEFT JOIN items i ON i.id=sb.item_id WHERE w.deleted_at IS NULL GROUP BY w.id ORDER BY w.status='ACTIVE' DESC,w.warehouse_code`);
    const zones = await this.db.query(`SELECT z.id,z.warehouse_id "warehouseId",z.code,z.name,z.actual_location "actualLocation",z.status,
      count(DISTINCT l.id) FILTER(WHERE l.status='ACTIVE' AND l.is_archived=false)::int "activeLocationCount",count(DISTINCT l.id) FILTER(WHERE l.is_archived=false)::int "locationCount",
      count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
      count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
      count(*) FILTER(WHERE sb.on_hand_qty=0)::int "zeroStockCount",max(sb.updated_at) "lastInventoryAt"
      FROM warehouse_zones z LEFT JOIN warehouse_locations l ON l.zone_id=z.id AND l.is_archived=false LEFT JOIN stock_balances sb ON sb.location_id=l.id
      LEFT JOIN items i ON i.id=sb.item_id WHERE z.deleted_at IS NULL GROUP BY z.id ORDER BY z.code`);
    const [totals] = await this.db.query(`SELECT count(DISTINCT w.id)::int "warehouseCount",count(DISTINCT w.id) FILTER(WHERE w.status='ACTIVE')::int "activeWarehouseCount",
      count(DISTINCT z.id) FILTER(WHERE z.status='ACTIVE' AND z.deleted_at IS NULL)::int "activeZoneCount",
      count(DISTINCT l.id) FILTER(WHERE l.status='ACTIVE' AND l.is_archived=false)::int "activeLocationCount",count(DISTINCT sb.item_id)::int "itemCount",
      count(DISTINCT sb.id)::int "inventoryRecordCount",count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
      count(DISTINCT sb.id) FILTER(WHERE w.warehouse_type='DEFECTIVE')::int "defectiveInventoryRecordCount"
      FROM warehouses w LEFT JOIN warehouse_zones z ON z.warehouse_id=w.id AND z.deleted_at IS NULL
      LEFT JOIN warehouse_locations l ON l.zone_id=z.id AND l.is_archived=false LEFT JOIN stock_balances sb ON sb.location_id=l.id LEFT JOIN items i ON i.id=sb.item_id
      WHERE w.deleted_at IS NULL`);
    return { totals, warehouses: warehouses.map((warehouse: any) => ({ ...warehouse, zones: zones.filter((zone: any) => zone.warehouseId === warehouse.id) })) };
  }

  @Get(':id/overview')
  @Permissions('warehouse.virtual.view')
  async overview(@Param('id') id: string) {
    const [warehouse] = await this.db.query(`SELECT * FROM warehouses WHERE id=$1`, [id]);
    if (!warehouse) return null;
    const [stats] = await this.db.query(`
      SELECT
        count(DISTINCT sb.item_id)::int "itemCategoryCount",
        coalesce(sum(sb.on_hand_qty),0)::text "totalStock",
        (SELECT count(*)::int FROM warehouse_locations WHERE warehouse_id=$1 AND status='ACTIVE') "totalLocations",
        count(DISTINCT sb.location_id)::int "usedLocations",
        count(*) FILTER (WHERE coalesce(sb.on_hand_qty,0)=0)::int "zeroStockCount",
        count(*) FILTER (WHERE coalesce(sb.on_hand_qty,0)>0 AND coalesce(sb.on_hand_qty,0)<=i.minimum_stock)::int "lowStockCount"
       FROM stock_balances sb
       JOIN items i ON i.id=sb.item_id
       WHERE sb.warehouse_id=$1
    `, [id]);
    return { ...warehouse, ...stats };
  }

  @Get(':id/locations')
  @Permissions('warehouse.virtual.view')
  async locations(@Param('id') id: string, @Query() q: any) {
    const params: any[] = [id];
    const where = ['l.warehouse_id=$1'];
    if (q.keyword) {
      params.push(`%${q.keyword}%`);
      where.push(`(i.item_code ILIKE $${params.length} OR i.name ILIKE $${params.length})`);
    }
    return this.db.query(`
      SELECT l.id,l.code,l.name,l.status,l.is_archived "isArchived",l.auto_generated "autoGenerated",l.system_default "systemDefault",l.sort_order "sortOrder",z.id "zoneId",z.code "zoneCode",z.name "zoneName",
        r.id "rackId",r.code "rackCode",r.name "rackName",l.layer,l.col_pos "colPos",l.position_desc "positionDesc",
        coalesce(sum(sb.on_hand_qty),0)::text "onHandQty",coalesce(sum(sb.frozen_qty),0)::text "frozenQty",
        count(DISTINCT sb.item_id)::int "itemCount",count(DISTINCT sb.id)::int "inventoryRecordCount",
        count(*) FILTER(WHERE sb.on_hand_qty>0 AND sb.on_hand_qty<=i.minimum_stock)::int "lowStockCount",
        count(*) FILTER(WHERE sb.on_hand_qty=0)::int "zeroStockCount",count(DISTINCT i.unit)::int "unitCount",max(sb.updated_at) "lastInventoryAt"
      FROM warehouse_locations l
      LEFT JOIN warehouse_zones z ON z.id=l.zone_id
      LEFT JOIN warehouse_racks r ON r.id=l.rack_id
      LEFT JOIN stock_balances sb ON sb.location_id=l.id AND sb.warehouse_id=l.warehouse_id
      LEFT JOIN items i ON i.id=sb.item_id
      WHERE ${where.join(' AND ')}
      GROUP BY l.id,z.id,r.id ORDER BY z.code,l.code
    `, params);
  }

  @Get(':id/locations/:locId/stock')
  @Permissions('warehouse.virtual.view')
  async locationStock(@Param('id') id: string, @Param('locId') locId: string) {
    return this.db.query(`
      SELECT sb.id,i.id "itemId",i.item_code "itemCode",i.name "itemName",i.model,i.spec,i.unit,
        sb.on_hand_qty "onHandQty",sb.frozen_qty "frozenQty",b.batch_no "batchNo"
      FROM stock_balances sb
      JOIN items i ON i.id=sb.item_id
      LEFT JOIN inventory_batches b ON b.id=sb.batch_id
      WHERE sb.location_id=$1 AND sb.warehouse_id=$2
      ORDER BY i.item_code
    `, [locId, id]);
  }

  @Get(':id/layouts')
  @Permissions('warehouse.virtual.view')
  async listLayouts(@Param('id') id: string) {
    return this.db.query(
      `SELECT id,layout_name "layoutName",layout_type "layoutType",version,status,canvas_width "canvasWidth",canvas_height "canvasHeight",
        created_by_name "createdByName",published_by_name "publishedByName",published_at "publishedAt",created_at "createdAt"
       FROM warehouse_layouts WHERE warehouse_id=$1 ORDER BY version DESC`,
      [id],
    );
  }

  @Post(':id/layouts')
  @Permissions('warehouse.layout.edit')
  async createLayout(@Param('id') id: string, @Body() dto: any, @CurrentUser() u: AuthUser) {
    const snap = snapshotUser(u);
    const layoutId = randomUUID();
    await this.db.query(
      `INSERT INTO warehouse_layouts(id,warehouse_id,layout_name,layout_type,canvas_width,canvas_height,background_image,created_by_user_id,created_by_username,created_by_name)
       VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
      [layoutId, id, dto.layoutName, dto.layoutType || '2D', dto.canvasWidth || 1200, dto.canvasHeight || 800, dto.backgroundImage || null,
        snap.userId, snap.username, snap.name],
    );
    return { id: layoutId };
  }

  @Put(':id/layouts/:layoutId/nodes')
  @Permissions('warehouse.layout.edit')
  async saveNodes(@Param('id') id: string, @Param('layoutId') layoutId: string, @Body() dto: { nodes: any[] }) {
    await this.db.query(`DELETE FROM warehouse_visual_nodes WHERE layout_id=$1`, [layoutId]);
    for (const node of dto.nodes) {
      await this.db.query(
        `INSERT INTO warehouse_visual_nodes(id,layout_id,node_type,business_id,parent_node_id,code,name,x,y,width,height,rotation,layer,style_config)
         VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,
        [randomUUID(), layoutId, node.nodeType, node.businessId || null, node.parentNodeId || null,
          node.code, node.name, node.x || 0, node.y || 0, node.width || 100, node.height || 100,
          node.rotation || 0, node.layer || 0, node.styleConfig ? JSON.stringify(node.styleConfig) : null],
      );
    }
    return { ok: true };
  }

  @Post(':id/layouts/:layoutId/publish')
  @Permissions('warehouse.layout.edit')
  async publishLayout(@Param('id') id: string, @Param('layoutId') layoutId: string, @CurrentUser() u: AuthUser) {
    const snap = snapshotUser(u);
    await this.db.query(
      `UPDATE warehouse_layouts SET status='PUBLISHED',published_by_user_id=$1,published_by_username=$2,published_by_name=$3,published_at=now(),updated_at=now()
       WHERE id=$4 AND warehouse_id=$5`,
      [snap.userId, snap.username, snap.name, layoutId, id],
    );
    await this.db.query(
      `UPDATE warehouse_layouts SET status='ARCHIVED' WHERE warehouse_id=$1 AND id!=$2 AND status='PUBLISHED'`,
      [id, layoutId],
    );
    return { ok: true };
  }

  @Get(':id/layouts/:layoutId/nodes')
  @Permissions('warehouse.virtual.view')
  async getNodes(@Param('id') id: string, @Param('layoutId') layoutId: string) {
    return this.db.query(
      `SELECT id,node_type "nodeType",business_id "businessId",parent_node_id "parentNodeId",code,name,
        x,y,width,height,rotation,layer,style_config "styleConfig",status
       FROM warehouse_visual_nodes WHERE layout_id=$1 ORDER BY layer,code`,
      [layoutId],
    );
  }
}
