export enum Role {
  ADMIN = 'ADMIN',
  WAREHOUSE = 'WAREHOUSE',
  PRODUCTION = 'PRODUCTION',
}

export enum ItemType {
  MATERIAL = 'MATERIAL',
  SEMI_FINISHED = 'SEMI_FINISHED',
  FINISHED_GOOD = 'FINISHED_GOOD',
}

export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum DocumentStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  POSTED = 'POSTED',
  VOIDED = 'VOIDED',
  CANCELLED = 'CANCELLED',
}

export enum DocumentType {
  MATERIAL_INBOUND = 'MATERIAL_INBOUND',
  FINISHED_INBOUND = 'FINISHED_INBOUND',
  PRODUCTION_ISSUE = 'PRODUCTION_ISSUE',
  PRODUCTION_RETURN = 'PRODUCTION_RETURN',
  PRODUCTION_COMPLETION = 'PRODUCTION_COMPLETION',
  FINISHED_OUTBOUND = 'FINISHED_OUTBOUND',
  INVENTORY_ADJUSTMENT = 'INVENTORY_ADJUSTMENT',
  STOCK_MOVE = 'STOCK_MOVE',
  STOCK_CHECK = 'STOCK_CHECK',
  DEFECTIVE_RETURN = 'DEFECTIVE_RETURN',
  DEFECTIVE_REPAIR_RESTOCK = 'DEFECTIVE_REPAIR_RESTOCK',
  DEFECTIVE_PRODUCTION_RETURN = 'DEFECTIVE_PRODUCTION_RETURN',
  REVERSAL = 'REVERSAL',
}

export enum Direction {
  IN = 'IN',
  OUT = 'OUT',
}

export enum ProductionStatus {
  DRAFT = 'DRAFT',
  RELEASED = 'RELEASED',
  AWAITING_ISSUE = 'AWAITING_ISSUE',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_COMPLETION = 'AWAITING_COMPLETION',
  COMPLETED = 'COMPLETED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export interface AuthUser {
  id: string;
  username: string;
  employeeName: string;
  employeeNo?: string;
  department?: string;
  position?: string;
  name: string;
  role: Role | string;
  roleId?: string;
  permissions?: string[];
}
