import { Injectable } from '@nestjs/common';
import Decimal from 'decimal.js';
import { DataSource, QueryRunner } from 'typeorm';
import { AuditService } from '../audit/audit.service';
import { BusinessException } from '../common/business.exception';
import { Direction, DocumentType, ItemType } from '../common/constants';
import { parsePage } from '../common/validation';
import { InventoryPostingService } from '../inventory/posting.service';

@Injectable()
export class StockDocumentsService{
  constructor(private readonly db:DataSource,private readonly posting:InventoryPostingService,private readonly audit:AuditService){}
  async create(type:DocumentType,dto:any,userId:string){
    const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const code=type===DocumentType.MATERIAL_INBOUND?'RAW':'FG';const [warehouse]=await qr.query(`SELECT id FROM warehouses WHERE warehouse_code=$1 AND status='ACTIVE'`,[code]);if(!warehouse)throw new BusinessException('NOT_FOUND',`${code}仓库不存在`);await this.validateManualLines(qr,type,dto.lines);const direction=[DocumentType.MATERIAL_INBOUND,DocumentType.FINISHED_INBOUND].includes(type)?Direction.IN:Direction.OUT;const doc=await this.posting.createDocument(qr,{documentType:type,warehouseId:warehouse.id,notes:dto.notes,lines:dto.lines.map((l:any)=>({...l,direction}))},userId);await this.audit.log(userId,'CREATE_STOCK_DOCUMENT','stock_documents',doc.id,{type},qr.manager);await qr.commitTransaction();return this.get(doc.id);}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  async update(id:string,dto:any,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [doc]=await qr.query(`SELECT * FROM stock_documents WHERE id=$1 FOR UPDATE`,[id]);if(!doc)throw new BusinessException('NOT_FOUND','库存单据不存在');if(doc.status!=='DRAFT')throw new BusinessException('INVALID_STATUS','已过账单据不可编辑');if(![DocumentType.MATERIAL_INBOUND,DocumentType.FINISHED_INBOUND,DocumentType.FINISHED_OUTBOUND].includes(doc.document_type))throw new BusinessException('INVALID_STATUS','生产单据不可在此编辑');await this.validateManualLines(qr,doc.document_type,dto.lines);const direction=[DocumentType.MATERIAL_INBOUND,DocumentType.FINISHED_INBOUND].includes(doc.document_type)?Direction.IN:Direction.OUT;await qr.query(`UPDATE stock_documents SET notes=$1,updated_at=now() WHERE id=$2`,[dto.notes||null,id]);await qr.query(`DELETE FROM stock_document_lines WHERE document_id=$1`,[id]);for(const l of dto.lines)await qr.query(`INSERT INTO stock_document_lines(id,document_id,item_id,quantity,direction,notes) VALUES(gen_random_uuid(),$1,$2,$3,$4,$5)`,[id,l.itemId,l.quantity,direction,l.notes||null]);await this.audit.log(userId,'UPDATE_STOCK_DOCUMENT','stock_documents',id,undefined,qr.manager);await qr.commitTransaction();return this.get(id);}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  async remove(id:string,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [doc]=await qr.query(`SELECT status FROM stock_documents WHERE id=$1 FOR UPDATE`,[id]);if(!doc)throw new BusinessException('NOT_FOUND','库存单据不存在');if(doc.status!=='DRAFT')throw new BusinessException('INVALID_STATUS','已过账单据不可删除');await this.audit.log(userId,'DELETE_STOCK_DOCUMENT','stock_documents',id,undefined,qr.manager);await qr.query(`DELETE FROM stock_documents WHERE id=$1`,[id]);await qr.commitTransaction();return {id};}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  post(id:string,key:string|undefined,userId:string){return this.posting.executeIdempotent(userId,key,`POST:/stock-documents/:id/post`,{id},qr=>this.posting.applyDocument(qr,id,userId));}
  void(id:string,reason:string|undefined,key:string|undefined,userId:string){return this.posting.executeIdempotent(userId,key,`POST:/stock-documents/:id/void`,{id,reason:reason||null},async qr=>{
    const [original]=await qr.query(`SELECT * FROM stock_documents WHERE id=$1 FOR UPDATE`,[id]);if(!original)throw new BusinessException('NOT_FOUND','库存单据不存在');if(original.status!=='POSTED')throw new BusinessException('INVALID_STATUS','只有已过账单据可以冲销');if(original.document_type===DocumentType.REVERSAL)throw new BusinessException('INVALID_STATUS','冲销单不能再次冲销');
    const lines=await qr.query(`SELECT item_id,quantity,direction FROM stock_document_lines WHERE document_id=$1 ORDER BY item_id`,[id]);const reversal=await this.posting.createDocument(qr,{documentType:DocumentType.REVERSAL,warehouseId:original.warehouse_id,productionOrderId:original.production_order_id,originalDocumentId:id,notes:reason||`冲销 ${original.document_no}`,lines:lines.map((l:any)=>({itemId:l.item_id,quantity:l.quantity,direction:l.direction===Direction.IN?Direction.OUT:Direction.IN}))},userId);
    const posted=await this.posting.applyDocument(qr,reversal.id,userId);await qr.query(`UPDATE stock_documents SET status='VOIDED',voided_by=$1,voided_at=now(),updated_at=now() WHERE id=$2`,[userId,id]);if(original.production_order_id)await this.reverseProduction(qr,original,lines);
    await this.audit.log(userId,'VOID_STOCK_DOCUMENT','stock_documents',id,{reversalId:reversal.id,reason},qr.manager);return {...posted,originalDocumentId:id};
  });}
  private async reverseProduction(qr:QueryRunner,doc:any,lines:any[]){
    if(doc.document_type===DocumentType.PRODUCTION_ISSUE||doc.document_type===DocumentType.PRODUCTION_RETURN){const column=doc.document_type===DocumentType.PRODUCTION_ISSUE?'issued_qty':'returned_qty';for(const line of lines)await qr.query(`UPDATE production_order_materials SET ${column}=${column}-$1 WHERE production_order_id=$2 AND material_id=$3`,[line.quantity,doc.production_order_id,line.item_id]);}
    if(doc.document_type===DocumentType.PRODUCTION_COMPLETION){const total=lines.reduce((s:Decimal,l:any)=>s.add(l.quantity),new Decimal(0));await qr.query(`UPDATE production_orders SET completed_qty=completed_qty-$1 WHERE id=$2`,[total.toFixed(4),doc.production_order_id]);}
    const materials=await qr.query(`SELECT issued_qty,returned_qty FROM production_order_materials WHERE production_order_id=$1`,[doc.production_order_id]);if(materials.some((m:any)=>new Decimal(m.returned_qty).gt(m.issued_qty)))throw new BusinessException('INVALID_STATUS','冲销后退料量将超过领料量');const [order]=await qr.query(`SELECT planned_qty,completed_qty,status FROM production_orders WHERE id=$1 FOR UPDATE`,[doc.production_order_id]);if(order.status==='CANCELLED'&&materials.some((m:any)=>!new Decimal(m.issued_qty).sub(m.returned_qty).isZero()))throw new BusinessException('INVALID_STATUS','取消任务冲销后会产生未退净领料');if(order.status!=='CANCELLED'){const [activity]=await qr.query(`SELECT count(*)::int count FROM stock_documents WHERE production_order_id=$1 AND status='POSTED' AND document_type IN ('PRODUCTION_ISSUE','PRODUCTION_RETURN','PRODUCTION_COMPLETION')`,[doc.production_order_id]);const status=new Decimal(order.completed_qty).eq(order.planned_qty)?'COMPLETED':activity.count>0?'IN_PROGRESS':'RELEASED';await qr.query(`UPDATE production_orders SET status=$1,updated_at=now() WHERE id=$2`,[status,doc.production_order_id]);}
  }
  private async validateManualLines(qr:QueryRunner,type:DocumentType,lines:any[]){
    if(new Set(lines.map(line=>line.itemId)).size!==lines.length)throw new BusinessException('VALIDATION_ERROR','同一物料不能重复');
    const ids=lines.map(line=>line.itemId);
    const items=await qr.query(`SELECT id,item_type,status FROM items WHERE id=ANY($1::uuid[])`,[ids]);
    if(items.length!==ids.length)throw new BusinessException('VALIDATION_ERROR','单据包含不存在的物料');
    if(items.some((item:any)=>item.status!=='ACTIVE'))throw new BusinessException('VALIDATION_ERROR','单据只能包含启用物料');
    const expected=type===DocumentType.MATERIAL_INBOUND?ItemType.MATERIAL:ItemType.FINISHED_GOOD;
    if(items.some((item:any)=>item.item_type!==expected))throw new BusinessException('VALIDATION_ERROR',expected===ItemType.MATERIAL?'原材料入库只能包含原材料':'成品入库或出库只能包含成品');
  }
  async get(id:string){const [doc]=await this.db.query(`SELECT d.id,d.document_no "documentNo",d.document_type "documentType",d.status,d.notes,d.production_order_id "productionOrderId",d.original_document_id "originalDocumentId",w.id "warehouseId",w.warehouse_code "warehouseCode",w.name "warehouseName",d.created_at "createdAt",d.posted_at "postedAt",d.voided_at "voidedAt",u.username "createdBy" FROM stock_documents d JOIN warehouses w ON w.id=d.warehouse_id JOIN users u ON u.id=d.created_by WHERE d.id=$1`,[id]);if(!doc)throw new BusinessException('NOT_FOUND','库存单据不存在');doc.lines=await this.db.query(`SELECT l.id,i.id "itemId",i.item_code "itemCode",i.name "itemName",i.unit,l.quantity,l.direction,l.notes FROM stock_document_lines l JOIN items i ON i.id=l.item_id WHERE l.document_id=$1 ORDER BY i.item_code`,[id]);return doc;}
  async list(q:any){const page=parsePage(q.page,1),pageSize=parsePage(q.pageSize,20,100),offset=(page-1)*pageSize;const p:any[]=[];const w:string[]=[];if(q.documentType){p.push(q.documentType);w.push(`d.document_type=$${p.length}`);}if(q.status){p.push(q.status);w.push(`d.status=$${p.length}`);}if(q.keyword){p.push(`%${q.keyword}%`);w.push(`d.document_no ILIKE $${p.length}`);}if(q.dateFrom){p.push(q.dateFrom);w.push(`d.created_at >= $${p.length}::date`);}if(q.dateTo){p.push(q.dateTo);w.push(`d.created_at < ($${p.length}::date + interval '1 day')`);}const clause=w.length?`WHERE ${w.join(' AND ')}`:'';const [{count}]=await this.db.query(`SELECT count(*)::int count FROM stock_documents d ${clause}`,p);p.push(pageSize,offset);const rows=await this.db.query(`SELECT d.id,d.document_no "documentNo",d.document_type "documentType",d.status,d.notes,w.warehouse_code "warehouseCode",d.production_order_id "productionOrderId",d.created_at "createdAt",d.posted_at "postedAt" FROM stock_documents d JOIN warehouses w ON w.id=d.warehouse_id ${clause} ORDER BY d.created_at DESC LIMIT $${p.length-1} OFFSET $${p.length}`,p);return {items:rows,total:count,page,pageSize};}
}
