import { HttpStatus, Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import Decimal from 'decimal.js';
import { DataSource, QueryRunner } from 'typeorm';
import { AuditService } from '../audit/audit.service';
import { BusinessException } from '../common/business.exception';
import { Direction, DocumentType, ProductionStatus } from '../common/constants';
import { parsePage } from '../common/validation';
import { InventoryPostingService } from '../inventory/posting.service';

@Injectable()
export class ProductionService{
  constructor(private readonly db:DataSource,private readonly posting:InventoryPostingService,private readonly audit:AuditService){}
  async create(dto:any,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [fg]=await qr.query(`SELECT id FROM items WHERE id=$1 AND item_type='FINISHED_GOOD' AND status='ACTIVE'`,[dto.finishedGoodId]);if(!fg)throw new BusinessException('VALIDATION_ERROR','成品不存在或已停用');const [bom]=await qr.query(`SELECT id FROM boms WHERE finished_good_id=$1 AND status='ACTIVE'`,[dto.finishedGoodId]);if(!bom)throw new BusinessException('VALIDATION_ERROR','成品没有启用BOM');const lines=await qr.query(`SELECT material_id,qty_per FROM bom_items WHERE bom_id=$1 ORDER BY material_id`,[bom.id]);if(!lines.length)throw new BusinessException('VALIDATION_ERROR','BOM没有材料明细');const id=randomUUID(),orderNo=`PO-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${randomUUID().slice(0,8).toUpperCase()}`;await qr.query(`INSERT INTO production_orders(id,order_no,finished_good_id,planned_qty,planned_date,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,orderNo,dto.finishedGoodId,dto.plannedQty,dto.plannedDate||null,dto.notes||null,userId]);for(const l of lines){const required=new Decimal(l.qty_per).mul(dto.plannedQty).toFixed(4);await qr.query(`INSERT INTO production_order_materials(id,production_order_id,material_id,qty_per,required_qty) VALUES($1,$2,$3,$4,$5)`,[randomUUID(),id,l.material_id,l.qty_per,required]);}await this.audit.log(userId,'CREATE_PRODUCTION_ORDER','production_orders',id,{orderNo},qr.manager);await qr.commitTransaction();return this.get(id);}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  async update(id:string,dto:any,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [order]=await qr.query(`SELECT * FROM production_orders WHERE id=$1 FOR UPDATE`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');if(order.status!==ProductionStatus.DRAFT)throw new BusinessException('INVALID_STATUS','只有草稿任务可以编辑');const qty=dto.plannedQty||order.planned_qty;await qr.query(`UPDATE production_orders SET planned_qty=$1,planned_date=$2,notes=$3,updated_at=now() WHERE id=$4`,[qty,dto.plannedDate??order.planned_date,dto.notes??order.notes,id]);await qr.query(`UPDATE production_order_materials SET required_qty=qty_per*$1 WHERE production_order_id=$2`,[qty,id]);await this.audit.log(userId,'UPDATE_PRODUCTION_ORDER','production_orders',id,dto,qr.manager);await qr.commitTransaction();return this.get(id);}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  async shortages(id:string,manager?:any){const db=manager||this.db;const [order]=await db.query(`SELECT id FROM production_orders WHERE id=$1`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');return db.query(`SELECT m.material_id "materialId",i.item_code "itemCode",i.name,m.required_qty "requiredQty",COALESCE(b.on_hand_qty,0) "availableQty",GREATEST(m.required_qty-COALESCE(b.on_hand_qty,0),0) "shortageQty" FROM production_order_materials m JOIN items i ON i.id=m.material_id JOIN warehouses w ON w.warehouse_code='RAW' LEFT JOIN stock_balances b ON b.warehouse_id=w.id AND b.item_id=m.material_id WHERE m.production_order_id=$1 AND COALESCE(b.on_hand_qty,0)<m.required_qty ORDER BY i.item_code`,[id]);}
  async release(id:string,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [order]=await qr.query(`SELECT status FROM production_orders WHERE id=$1 FOR UPDATE`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');if(order.status!==ProductionStatus.DRAFT)throw new BusinessException('INVALID_STATUS','只有草稿任务可以发布');const shortages=await this.shortages(id,qr);if(shortages.length)throw new BusinessException('INSUFFICIENT_STOCK','存在缺料，不能发布',HttpStatus.CONFLICT,shortages);await qr.query(`UPDATE production_orders SET status='RELEASED',shortage_flag=false,released_at=now(),updated_at=now() WHERE id=$1`,[id]);await this.audit.log(userId,'RELEASE_PRODUCTION_ORDER','production_orders',id,undefined,qr.manager);await qr.commitTransaction();return this.get(id);}catch(e:any){await qr.rollbackTransaction();if(e?.errorCode==='INSUFFICIENT_STOCK')await this.db.query(`UPDATE production_orders SET shortage_flag=true,updated_at=now() WHERE id=$1`,[id]);throw e;}finally{await qr.release();}}
  issue(id:string,dto:any,key:string|undefined,userId:string){return this.posting.executeIdempotent(userId,key,'POST:/production-orders/:id/issue',{id,...dto},async qr=>{const order=await this.lockActionable(qr,id);this.uniqueLines(dto.lines);const mats=await this.materialMap(qr,id);for(const l of dto.lines){const m=mats.get(l.materialId);if(!m)throw new BusinessException('VALIDATION_ERROR','领料物料不属于任务BOM');const after=new Decimal(m.issued_qty).sub(m.returned_qty).add(l.quantity);if(after.gt(new Decimal(m.required_qty).mul('1.1')))throw new BusinessException('VALIDATION_ERROR',`${m.item_code} 累计净领料不能超过需求量110%`);}const warehouse=await this.warehouse(qr,'RAW');const doc=await this.posting.createDocument(qr,{documentType:DocumentType.PRODUCTION_ISSUE,warehouseId:warehouse.id,productionOrderId:id,notes:dto.notes,lines:dto.lines.map((l:any)=>({itemId:l.materialId,quantity:l.quantity,direction:Direction.OUT}))},userId);const result=await this.posting.applyDocument(qr,doc.id,userId);for(const l of dto.lines)await qr.query(`UPDATE production_order_materials SET issued_qty=issued_qty+$1 WHERE production_order_id=$2 AND material_id=$3`,[l.quantity,id,l.materialId]);await qr.query(`UPDATE production_orders SET status='IN_PROGRESS',updated_at=now() WHERE id=$1`,[id]);return result;});}
  returnMaterial(id:string,dto:any,key:string|undefined,userId:string){return this.posting.executeIdempotent(userId,key,'POST:/production-orders/:id/return',{id,...dto},async qr=>{await this.lockActionable(qr,id);this.uniqueLines(dto.lines);const mats=await this.materialMap(qr,id);for(const l of dto.lines){const m=mats.get(l.materialId);if(!m)throw new BusinessException('VALIDATION_ERROR','退料物料不属于任务BOM');if(new Decimal(l.quantity).gt(new Decimal(m.issued_qty).sub(m.returned_qty)))throw new BusinessException('VALIDATION_ERROR',`${m.item_code} 退料量超过当前净领料量`);}const warehouse=await this.warehouse(qr,'RAW');const doc=await this.posting.createDocument(qr,{documentType:DocumentType.PRODUCTION_RETURN,warehouseId:warehouse.id,productionOrderId:id,notes:dto.notes,lines:dto.lines.map((l:any)=>({itemId:l.materialId,quantity:l.quantity,direction:Direction.IN}))},userId);const result=await this.posting.applyDocument(qr,doc.id,userId);for(const l of dto.lines)await qr.query(`UPDATE production_order_materials SET returned_qty=returned_qty+$1 WHERE production_order_id=$2 AND material_id=$3`,[l.quantity,id,l.materialId]);await qr.query(`UPDATE production_orders SET status='IN_PROGRESS',updated_at=now() WHERE id=$1`,[id]);return result;});}
  complete(id:string,dto:any,key:string|undefined,userId:string){return this.posting.executeIdempotent(userId,key,'POST:/production-orders/:id/complete',{id,...dto},async qr=>{const order=await this.lockActionable(qr,id);const after=new Decimal(order.completed_qty).add(dto.quantity);if(after.gt(order.planned_qty))throw new BusinessException('VALIDATION_ERROR',`累计完工不能超过计划数量 ${order.planned_qty}`);const warehouse=await this.warehouse(qr,'FG');const doc=await this.posting.createDocument(qr,{documentType:DocumentType.PRODUCTION_COMPLETION,warehouseId:warehouse.id,productionOrderId:id,notes:dto.notes,lines:[{itemId:order.finished_good_id,quantity:dto.quantity,direction:Direction.IN}]},userId);const result=await this.posting.applyDocument(qr,doc.id,userId);const status=after.eq(order.planned_qty)?ProductionStatus.COMPLETED:ProductionStatus.IN_PROGRESS;await qr.query(`UPDATE production_orders SET completed_qty=$1,status=$2,updated_at=now() WHERE id=$3`,[after.toFixed(4),status,id]);return {...result,productionStatus:status,completedQty:after.toFixed(4)};});}
  async cancel(id:string,reason:string|undefined,userId:string){const qr=this.db.createQueryRunner();await qr.connect();await qr.startTransaction();try{const [order]=await qr.query(`SELECT status FROM production_orders WHERE id=$1 FOR UPDATE`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');if(![ProductionStatus.DRAFT,ProductionStatus.RELEASED,ProductionStatus.IN_PROGRESS].includes(order.status))throw new BusinessException('INVALID_STATUS','当前状态不能取消');const materials=await qr.query(`SELECT issued_qty,returned_qty FROM production_order_materials WHERE production_order_id=$1`,[id]);if(materials.some((m:any)=>!new Decimal(m.issued_qty).sub(m.returned_qty).isZero()))throw new BusinessException('INVALID_STATUS','存在未退净领料，必须先全部退料');await qr.query(`UPDATE production_orders SET status='CANCELLED',notes=CASE WHEN $1::text IS NULL THEN notes ELSE concat_ws(E'\n',notes,$1) END,updated_at=now() WHERE id=$2`,[reason||null,id]);await this.audit.log(userId,'CANCEL_PRODUCTION_ORDER','production_orders',id,{reason},qr.manager);await qr.commitTransaction();return this.get(id);}catch(e){await qr.rollbackTransaction();throw e;}finally{await qr.release();}}
  private async lockActionable(qr:QueryRunner,id:string){const [order]=await qr.query(`SELECT * FROM production_orders WHERE id=$1 FOR UPDATE`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');if(![ProductionStatus.RELEASED,ProductionStatus.IN_PROGRESS].includes(order.status))throw new BusinessException('INVALID_STATUS','任务必须已发布且未完成');return order;}
  private async materialMap(qr:QueryRunner,id:string){const rows:any[]=await qr.query(`SELECT m.*,i.item_code FROM production_order_materials m JOIN items i ON i.id=m.material_id WHERE production_order_id=$1 ORDER BY material_id FOR UPDATE OF m`,[id]);return new Map<string,any>(rows.map((r:any)=>[r.material_id,r]));}
  private async warehouse(qr:QueryRunner,code:string){const [w]=await qr.query(`SELECT id FROM warehouses WHERE warehouse_code=$1 AND status='ACTIVE'`,[code]);if(!w)throw new BusinessException('NOT_FOUND',`${code}仓库不存在`);return w;}
  private uniqueLines(lines:any[]){if(new Set(lines.map(l=>l.materialId)).size!==lines.length)throw new BusinessException('VALIDATION_ERROR','同一物料不能重复');}
  async get(id:string){const [order]=await this.db.query(`SELECT o.id,o.order_no "orderNo",o.finished_good_id "finishedGoodId",i.item_code "finishedGoodCode",i.name "finishedGoodName",i.unit,o.planned_qty "plannedQty",o.completed_qty "completedQty",o.status,o.shortage_flag "shortageFlag",o.planned_date "plannedDate",o.notes,o.created_at "createdAt",o.released_at "releasedAt" FROM production_orders o JOIN items i ON i.id=o.finished_good_id WHERE o.id=$1`,[id]);if(!order)throw new BusinessException('NOT_FOUND','生产任务不存在');order.materials=await this.db.query(`SELECT m.material_id "materialId",i.item_code "itemCode",i.name,i.unit,m.qty_per "qtyPer",m.required_qty "requiredQty",m.issued_qty "issuedQty",m.returned_qty "returnedQty",(m.issued_qty-m.returned_qty) "netIssuedQty",COALESCE(b.on_hand_qty,0) "rawOnHandQty" FROM production_order_materials m JOIN items i ON i.id=m.material_id JOIN warehouses w ON w.warehouse_code='RAW' LEFT JOIN stock_balances b ON b.warehouse_id=w.id AND b.item_id=m.material_id WHERE m.production_order_id=$1 ORDER BY i.item_code`,[id]);order.documents=await this.db.query(`SELECT id,document_no "documentNo",document_type "documentType",status,created_at "createdAt",posted_at "postedAt" FROM stock_documents WHERE production_order_id=$1 ORDER BY created_at DESC`,[id]);return order;}
  async list(q:any){const page=parsePage(q.page,1),pageSize=parsePage(q.pageSize,20,100),offset=(page-1)*pageSize;const p:any[]=[];const w:string[]=[];if(q.keyword){p.push(`%${q.keyword}%`);w.push(`(o.order_no ILIKE $${p.length} OR i.item_code ILIKE $${p.length} OR i.name ILIKE $${p.length})`);}if(q.status){p.push(q.status);w.push(`o.status=$${p.length}`);}if(q.dateFrom){p.push(q.dateFrom);w.push(`o.created_at >= $${p.length}::date`);}if(q.dateTo){p.push(q.dateTo);w.push(`o.created_at < ($${p.length}::date + interval '1 day')`);}const clause=w.length?`WHERE ${w.join(' AND ')}`:'';const [{count}]=await this.db.query(`SELECT count(*)::int count FROM production_orders o JOIN items i ON i.id=o.finished_good_id ${clause}`,p);p.push(pageSize,offset);const rows=await this.db.query(`SELECT o.id,o.order_no "orderNo",i.item_code "finishedGoodCode",i.name "finishedGoodName",o.planned_qty "plannedQty",o.completed_qty "completedQty",o.status,o.shortage_flag "shortageFlag",o.planned_date "plannedDate",o.created_at "createdAt" FROM production_orders o JOIN items i ON i.id=o.finished_good_id ${clause} ORDER BY o.created_at DESC LIMIT $${p.length-1} OFFSET $${p.length}`,p);return {items:rows,total:count,page,pageSize};}
}
